package edu.server.repositorio;

// default package
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8959011015785196257L;
	private int idCategoria;
	private String nombre;
	private Set<Insumo> insumos = new HashSet<Insumo>(0);

	public Categoria() {
	}

	public Categoria(int idCategoria, String nombre) {
		this.idCategoria = idCategoria;
		this.nombre = nombre;
	}

	public Categoria(int idCategoria, String nombre, Set <Insumo>insumos) {
		this.idCategoria = idCategoria;
		this.nombre = nombre;
		this.insumos = insumos;
	}

	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Insumo> getInsumos() {
		return this.insumos;
	}

	public void setInsumos(Set<Insumo> insumos) {
		this.insumos = insumos;
	}

}
