package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6129639574088322820L;
	private String idClase;
	private String nombre;
	private Set<Elemento> elementos = new HashSet<Elemento>(0);

	public Clase() {
	}

	public Clase(String idClase, String nombre) {
		this.idClase = idClase;
		this.nombre = nombre;
	}

	public Clase(String idClase, String nombre, Set<Elemento> elementos) {
		this.idClase = idClase;
		this.nombre = nombre;
		this.elementos = elementos;
	}

	public String getIdClase() {
		return this.idClase;
	}

	public void setIdClase(String idClase) {
		this.idClase = idClase;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Elemento> getElementos() {
		return this.elementos;
	}

	public void setElementos(Set<Elemento> elementos) {
		this.elementos = elementos;
	}

}
