package edu.server.repositorio;

// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ClaseEquipo generated by hbm2java
 */
public class ClaseEquipo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5409457371219700318L;
	private int idClaseEquipo;
	private String nombreClase;
	private String descripcion;
	private Set<SubclaseEquipo> subclaseEquipos = new HashSet<SubclaseEquipo>(0);

	public ClaseEquipo() {
	}

	public ClaseEquipo(int idClaseEquipo, String nombreClase) {
		this.idClaseEquipo = idClaseEquipo;
		this.nombreClase = nombreClase;
	}

	public ClaseEquipo(int idClaseEquipo, String nombreClase,
			String descripcion, Set<SubclaseEquipo> subclaseEquipos) {
		this.idClaseEquipo = idClaseEquipo;
		this.nombreClase = nombreClase;
		this.descripcion = descripcion;
		this.subclaseEquipos = subclaseEquipos;
	}

	public int getIdClaseEquipo() {
		return this.idClaseEquipo;
	}

	public void setIdClaseEquipo(int idClaseEquipo) {
		this.idClaseEquipo = idClaseEquipo;
	}

	public String getNombreClase() {
		return this.nombreClase;
	}

	public void setNombreClase(String nombreClase) {
		this.nombreClase = nombreClase;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<SubclaseEquipo> getSubclaseEquipos() {
		return this.subclaseEquipos;
	}

	public void setSubclaseEquipos(Set<SubclaseEquipo> subclaseEquipos) {
		this.subclaseEquipos = subclaseEquipos;
	}

}
