package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1417650084665779435L;
	private int idCliente;
	private Direccion direccion;
	private String nombre;
	private String cuit;
	private String responsable;
	private String rubro;
	private String telefono;
	private String mail;
	private String fax;
	private String paginaWeb;
	private String observaciones;
	private Set<OrdenPedido> ordenPedidos = new HashSet<OrdenPedido>(0);
	private Set<Contacto>contactos = new HashSet<Contacto>(0);
	
	
	public Cliente() {
	}
	
	


	public Cliente(int idCliente, Direccion direccion, String nombre,
			String cuit, String responsable) {
		this.idCliente = idCliente;
		this.direccion = direccion;
		this.nombre = nombre;
		this.cuit = cuit;
		this.responsable = responsable;
	}

	public Cliente(int idCliente, Direccion direccion, String nombre,
			String cuit, String responsable, String rubro, String telefono,
			String mail, String fax, String paginaWeb, String observaciones,
			Set <OrdenPedido>ordenPedidos, Set <Contacto>contactos) {
		this.idCliente = idCliente;
		this.direccion = direccion;
		this.nombre = nombre;
		this.cuit = cuit;
		this.responsable = responsable;
		this.rubro = rubro;
		this.telefono = telefono;
		this.mail = mail;
		this.fax = fax;
		this.paginaWeb = paginaWeb;
		this.observaciones = observaciones;
		this.ordenPedidos = ordenPedidos;
		this.contactos = contactos;
	}

	
	
	public Set<Contacto> getContactos() {
		return contactos;
	}

	public void setContactos(Set<Contacto> contactos) {
		this.contactos = contactos;
	}


	
	
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public Direccion getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	public String getRubro() {
		return this.rubro;
	}

	public void setRubro(String rubro) {
		this.rubro = rubro;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getPaginaWeb() {
		return this.paginaWeb;
	}

	public void setPaginaWeb(String paginaWeb) {
		this.paginaWeb = paginaWeb;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set<OrdenPedido> getOrdenPedidos() {
		return this.ordenPedidos;
	}

	public void setOrdenPedidos(Set<OrdenPedido> ordenPedidos) {
		this.ordenPedidos = ordenPedidos;
	}

}
