package edu.server.repositorio;

/**
 * CodigoProductoId generated by hbm2java
 */
public class CodigoProductoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5021785654576699265L;
	private String idCodigoProducto;
	private String idMaterial;
	private String idElemento;
	private String idClase;

	public CodigoProductoId() {
	}

	public CodigoProductoId(String idCodigoProducto, String idMaterial,
			String idElemento, String idClase) {
		this.idCodigoProducto = idCodigoProducto;
		this.idMaterial = idMaterial;
		this.idElemento = idElemento;
		this.idClase = idClase;
	}

	public String getIdCodigoProducto() {
		return this.idCodigoProducto;
	}

	public void setIdCodigoProducto(String idCodigoProducto) {
		this.idCodigoProducto = idCodigoProducto;
	}

	public String getIdMaterial() {
		return this.idMaterial;
	}

	public void setIdMaterial(String idMaterial) {
		this.idMaterial = idMaterial;
	}

	public String getIdElemento() {
		return this.idElemento;
	}

	public void setIdElemento(String idElemento) {
		this.idElemento = idElemento;
	}

	public String getIdClase() {
		return this.idClase;
	}

	public void setIdClase(String idClase) {
		this.idClase = idClase;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CodigoProductoId))
			return false;
		CodigoProductoId castOther = (CodigoProductoId) other;

		return ((this.getIdCodigoProducto() == castOther.getIdCodigoProducto()) || (this
				.getIdCodigoProducto() != null
				&& castOther.getIdCodigoProducto() != null && this
				.getIdCodigoProducto().equals(castOther.getIdCodigoProducto())))
				&& ((this.getIdMaterial() == castOther.getIdMaterial()) || (this
						.getIdMaterial() != null
						&& castOther.getIdMaterial() != null && this
						.getIdMaterial().equals(castOther.getIdMaterial())))
				&& ((this.getIdElemento() == castOther.getIdElemento()) || (this
						.getIdElemento() != null
						&& castOther.getIdElemento() != null && this
						.getIdElemento().equals(castOther.getIdElemento())))
				&& ((this.getIdClase() == castOther.getIdClase()) || (this
						.getIdClase() != null && castOther.getIdClase() != null && this
						.getIdClase().equals(castOther.getIdClase())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdCodigoProducto() == null ? 0 : this
						.getIdCodigoProducto().hashCode());
		result = 37
				* result
				+ (getIdMaterial() == null ? 0 : this.getIdMaterial()
						.hashCode());
		result = 37
				* result
				+ (getIdElemento() == null ? 0 : this.getIdElemento()
						.hashCode());
		result = 37 * result
				+ (getIdClase() == null ? 0 : this.getIdClase().hashCode());
		return result;
	}

}
