package edu.server.repositorio;

/**
 * CodigoProducto generated by hbm2java
 */
public class CodigoProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8101543740422212031L;
	private CodigoProductoId id;
	private Elemento elemento;
	private Material material;
	private int idCodigo;

	public CodigoProducto() {
	}

	public CodigoProducto(CodigoProductoId id, Elemento elemento,
			Material material, int idCodigo) {
		this.id = id;
		this.elemento = elemento;
		this.material = material;
		this.idCodigo = idCodigo;
	}

	public CodigoProductoId getId() {
		return this.id;
	}

	public void setId(CodigoProductoId id) {
		this.id = id;
	}

	public Elemento getElemento() {
		return this.elemento;
	}

	public void setElemento(Elemento elemento) {
		this.elemento = elemento;
	}

	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	public int getIdCodigo() {
		return this.idCodigo;
	}

	public void setIdCodigo(int idCodigo) {
		this.idCodigo = idCodigo;
	}

}
