package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Componente generated by hbm2java
 */
public class Componente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8690066507551279447L;
	private int idComponente;
	private String codigoComponente;
	private String descripcion;
	private int stockSeguridad;
	private int loteProduccion;
	private int cantidadInventario;
	private Set <RenglonOrdenProvisionInterna> renglonOrdenProvisionInternas = new HashSet<RenglonOrdenProvisionInterna>(0);
	private Set <RenglonOrdenPedido>renglonOrdenPedidos = new HashSet<RenglonOrdenPedido>(0);
	private Set <RenglonOrdenFabricacionGeneral> renglonOrdenFabricacionGenerals = new HashSet<RenglonOrdenFabricacionGeneral>(0);
	private Set <RenglonListaDeMateriales> renglonListaDeMaterialeses = new HashSet<RenglonListaDeMateriales>(0);
	private Set <RenglonOrdenTrabajo> renglonOrdenTrabajos = new HashSet<RenglonOrdenTrabajo>(0);

	public Componente() {
	}

	public Componente(int idComponente, String codigoComponente,
			int stockSeguridad, int loteProduccion, int cantidadInventario) {
		this.idComponente = idComponente;
		this.codigoComponente = codigoComponente;
		this.stockSeguridad = stockSeguridad;
		this.loteProduccion = loteProduccion;
		this.cantidadInventario = cantidadInventario;
	}

	public Componente(int idComponente, String codigoComponente,
			String descripcion, int stockSeguridad, int loteProduccion,
			int cantidadInventario, Set<RenglonOrdenProvisionInterna> renglonOrdenProvisionInternas,
			Set <RenglonOrdenPedido>renglonOrdenPedidos, Set <RenglonOrdenFabricacionGeneral> renglonOrdenFabricacionGenerals,
			Set <RenglonListaDeMateriales>renglonListaDeMaterialeses, Set <RenglonOrdenTrabajo>renglonOrdenTrabajos) {
		this.idComponente = idComponente;
		this.codigoComponente = codigoComponente;
		this.descripcion = descripcion;
		this.stockSeguridad = stockSeguridad;
		this.loteProduccion = loteProduccion;
		this.cantidadInventario = cantidadInventario;
		this.renglonOrdenProvisionInternas = renglonOrdenProvisionInternas;
		this.renglonOrdenPedidos = renglonOrdenPedidos;
		this.renglonOrdenFabricacionGenerals = renglonOrdenFabricacionGenerals;
		this.renglonListaDeMaterialeses = renglonListaDeMaterialeses;
		this.renglonOrdenTrabajos = renglonOrdenTrabajos;
	}

	public int getIdComponente() {
		return this.idComponente;
	}

	public void setIdComponente(int idComponente) {
		this.idComponente = idComponente;
	}

	public String getCodigoComponente() {
		return this.codigoComponente;
	}

	public void setCodigoComponente(String codigoComponente) {
		this.codigoComponente = codigoComponente;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getStockSeguridad() {
		return this.stockSeguridad;
	}

	public void setStockSeguridad(int stockSeguridad) {
		this.stockSeguridad = stockSeguridad;
	}

	public int getLoteProduccion() {
		return this.loteProduccion;
	}

	public void setLoteProduccion(int loteProduccion) {
		this.loteProduccion = loteProduccion;
	}

	public int getCantidadInventario() {
		return this.cantidadInventario;
	}

	public void setCantidadInventario(int cantidadInventario) {
		this.cantidadInventario = cantidadInventario;
	}

	public Set<RenglonOrdenProvisionInterna> getRenglonOrdenProvisionInternas() {
		return this.renglonOrdenProvisionInternas;
	}

	public void setRenglonOrdenProvisionInternas(
			Set<RenglonOrdenProvisionInterna> renglonOrdenProvisionInternas) {
		this.renglonOrdenProvisionInternas = renglonOrdenProvisionInternas;
	}

	public Set <RenglonOrdenPedido>getRenglonOrdenPedidos() {
		return this.renglonOrdenPedidos;
	}

	public void setRenglonOrdenPedidos(Set <RenglonOrdenPedido>renglonOrdenPedidos) {
		this.renglonOrdenPedidos = renglonOrdenPedidos;
	}

	public Set <RenglonOrdenFabricacionGeneral> getRenglonOrdenFabricacionGenerals() {
		return this.renglonOrdenFabricacionGenerals;
	}

	public void setRenglonOrdenFabricacionGenerals(
			Set <RenglonOrdenFabricacionGeneral>renglonOrdenFabricacionGenerals) {
		this.renglonOrdenFabricacionGenerals = renglonOrdenFabricacionGenerals;
	}

	public Set<RenglonListaDeMateriales> getRenglonListaDeMaterialeses() {
		return this.renglonListaDeMaterialeses;
	}

	public void setRenglonListaDeMaterialeses(Set <RenglonListaDeMateriales>renglonListaDeMaterialeses) {
		this.renglonListaDeMaterialeses = renglonListaDeMaterialeses;
	}

	public Set <RenglonOrdenTrabajo> getRenglonOrdenTrabajos() {
		return this.renglonOrdenTrabajos;
	}

	public void setRenglonOrdenTrabajos(Set <RenglonOrdenTrabajo> renglonOrdenTrabajos) {
		this.renglonOrdenTrabajos = renglonOrdenTrabajos;
	}

}
