package edu.server.repositorio;

/**
 * Contacto generated by hbm2java
 */
public class Contacto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2291351395302753444L;
	private int idContacto;
	private Proveedor proveedor;
	private Cliente cliente;
	private String nombre;
	private String cargo;
	private String telefonoEmpresa;
	private String internoEmpresa;
	private String telefonoParticular;
	private String celular;
	private String mail;

	public Contacto() {
	}

	public Contacto(int idContacto, String nombre) {
		this.idContacto = idContacto;
		this.nombre = nombre;
	}

	public Contacto(int idContacto, Proveedor proveedor, Cliente cliente,
			String nombre, String cargo, String telefonoEmpresa,
			String internoEmpresa, String telefonoParticular, String celular,
			String mail) {
		this.idContacto = idContacto;
		this.proveedor = proveedor;
		this.cliente = cliente;
		this.nombre = nombre;
		this.cargo = cargo;
		this.telefonoEmpresa = telefonoEmpresa;
		this.internoEmpresa = internoEmpresa;
		this.telefonoParticular = telefonoParticular;
		this.celular = celular;
		this.mail = mail;
	}

	public int getIdContacto() {
		return this.idContacto;
	}

	public void setIdContacto(int idContacto) {
		this.idContacto = idContacto;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getTelefonoEmpresa() {
		return this.telefonoEmpresa;
	}

	public void setTelefonoEmpresa(String telefonoEmpresa) {
		this.telefonoEmpresa = telefonoEmpresa;
	}

	public String getInternoEmpresa() {
		return this.internoEmpresa;
	}

	public void setInternoEmpresa(String internoEmpresa) {
		this.internoEmpresa = internoEmpresa;
	}

	public String getTelefonoParticular() {
		return this.telefonoParticular;
	}

	public void setTelefonoParticular(String telefonoParticular) {
		this.telefonoParticular = telefonoParticular;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

}
