package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * ElementoId generated by hbm2java
 */
public class ElementoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1219601624414782294L;
	private String idElemento;
	private String idClase;

	public ElementoId() {
	}

	public ElementoId(String idElemento, String idClase) {
		this.idElemento = idElemento;
		this.idClase = idClase;
	}

	public String getIdElemento() {
		return this.idElemento;
	}

	public void setIdElemento(String idElemento) {
		this.idElemento = idElemento;
	}

	public String getIdClase() {
		return this.idClase;
	}

	public void setIdClase(String idClase) {
		this.idClase = idClase;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElementoId))
			return false;
		ElementoId castOther = (ElementoId) other;

		return ((this.getIdElemento() == castOther.getIdElemento()) || (this
				.getIdElemento() != null && castOther.getIdElemento() != null && this
				.getIdElemento().equals(castOther.getIdElemento())))
				&& ((this.getIdClase() == castOther.getIdClase()) || (this
						.getIdClase() != null && castOther.getIdClase() != null && this
						.getIdClase().equals(castOther.getIdClase())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdElemento() == null ? 0 : this.getIdElemento()
						.hashCode());
		result = 37 * result
				+ (getIdClase() == null ? 0 : this.getIdClase().hashCode());
		return result;
	}

}
