package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6975460052310325712L;
	private int idEmpleado;
	private String nombre;
	private String apellido;
	private int nroLegajo;
	private String puesto;
	private String codigoBarras;
	private Set <OrdenCompraInsumo> ordenCompraInsumos = new HashSet<OrdenCompraInsumo>(0);
	private Set <RemitoMateriales> remitoMaterialeses = new HashSet<RemitoMateriales>(0);
	private Set <RenglonOrdenTrabajo> renglonOrdenTrabajos = new HashSet<RenglonOrdenTrabajo>(0);
	private Set <IngresoProductos> ingresoProductoses = new HashSet<IngresoProductos>(0);
	private Set <OrdenPedido> ordenPedidos = new HashSet<OrdenPedido>(0);
	private Set <OrdenProvisionInterna> ordenProvisionInternas = new HashSet<OrdenProvisionInterna>(0);
	private Set <OrdenTrabajoSectorTercero> ordenTrabajoSectorTerceros = new HashSet<OrdenTrabajoSectorTercero>(0);
	private Set <IngresoInsumos>ingresoInsumoses = new HashSet<IngresoInsumos>(0);
	private Set <RemitoInternoInsumo>remitoInternoInsumos = new HashSet<RemitoInternoInsumo>(0);
	private Set <OrdenCompraCotizacion>ordenCompraCotizacions = new HashSet<OrdenCompraCotizacion>(0);
	private Set <Usuario>usuarios = new HashSet<Usuario>(0);
	private Set empleadosForEmpleado = new HashSet(0);
	private Set ordenProvisionInsumosForIdPedidoPara = new HashSet(0);
	private Set ordenProvisionInsumosForIdPedidoPor = new HashSet(0);
	private Set <OrdenFabricacionGeneral>ordenFabricacionGenerals = new HashSet<OrdenFabricacionGeneral>(0);
	private Set empleadosForResponsable = new HashSet(0);

	public Empleado() {
	}

	public Empleado(int idEmpleado, String nombre, String apellido,
			int nroLegajo, String puesto) {
		this.idEmpleado = idEmpleado;
		this.nombre = nombre;
		this.apellido = apellido;
		this.nroLegajo = nroLegajo;
		this.puesto = puesto;
	}

	public Empleado(int idEmpleado, String nombre, String apellido,
			int nroLegajo, String puesto, String codigoBarras,
			Set <OrdenCompraInsumo> ordenCompraInsumos, Set <RemitoMateriales> remitoMaterialeses,
			Set <RenglonOrdenTrabajo>renglonOrdenTrabajos, Set <IngresoProductos> ingresoProductoses, Set <OrdenPedido> ordenPedidos,
			Set <OrdenProvisionInterna>ordenProvisionInternas, Set <OrdenTrabajoSectorTercero>ordenTrabajoSectorTerceros,
			Set <IngresoInsumos>ingresoInsumoses, Set <RemitoInternoInsumo>remitoInternoInsumos,
			Set <OrdenCompraCotizacion>ordenCompraCotizacions, Set<Usuario> usuarios, Set empleadosForEmpleado,
			Set ordenProvisionInsumosForIdPedidoPara,
			Set ordenProvisionInsumosForIdPedidoPor,
			Set <OrdenFabricacionGeneral>ordenFabricacionGenerals, Set empleadosForResponsable) {
		this.idEmpleado = idEmpleado;
		this.nombre = nombre;
		this.apellido = apellido;
		this.nroLegajo = nroLegajo;
		this.puesto = puesto;
		this.codigoBarras = codigoBarras;
		this.ordenCompraInsumos = ordenCompraInsumos;
		this.remitoMaterialeses = remitoMaterialeses;
		this.renglonOrdenTrabajos = renglonOrdenTrabajos;
		this.ingresoProductoses = ingresoProductoses;
		this.ordenPedidos = ordenPedidos;
		this.ordenProvisionInternas = ordenProvisionInternas;
		this.ordenTrabajoSectorTerceros = ordenTrabajoSectorTerceros;
		this.ingresoInsumoses = ingresoInsumoses;
		this.remitoInternoInsumos = remitoInternoInsumos;
		this.ordenCompraCotizacions = ordenCompraCotizacions;
		this.usuarios = usuarios;
		this.empleadosForEmpleado = empleadosForEmpleado;
		this.ordenProvisionInsumosForIdPedidoPara = ordenProvisionInsumosForIdPedidoPara;
		this.ordenProvisionInsumosForIdPedidoPor = ordenProvisionInsumosForIdPedidoPor;
		this.ordenFabricacionGenerals = ordenFabricacionGenerals;
		this.empleadosForResponsable = empleadosForResponsable;
	}

	public int getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public int getNroLegajo() {
		return this.nroLegajo;
	}

	public void setNroLegajo(int nroLegajo) {
		this.nroLegajo = nroLegajo;
	}

	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	public String getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(String codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	public Set <OrdenCompraInsumo>getOrdenCompraInsumos() {
		return this.ordenCompraInsumos;
	}

	public void setOrdenCompraInsumos(Set<OrdenCompraInsumo> ordenCompraInsumos) {
		this.ordenCompraInsumos = ordenCompraInsumos;
	}

	public Set <RemitoMateriales> getRemitoMaterialeses() {
		return this.remitoMaterialeses;
	}

	public void setRemitoMaterialeses(Set <RemitoMateriales> remitoMaterialeses) {
		this.remitoMaterialeses = remitoMaterialeses;
	}

	public Set <RenglonOrdenTrabajo> getRenglonOrdenTrabajos() {
		return this.renglonOrdenTrabajos;
	}

	public void setRenglonOrdenTrabajos(Set <RenglonOrdenTrabajo> renglonOrdenTrabajos) {
		this.renglonOrdenTrabajos = renglonOrdenTrabajos;
	}

	public Set <IngresoProductos> getIngresoProductoses() {
		return this.ingresoProductoses;
	}

	public void setIngresoProductoses(Set <IngresoProductos> ingresoProductoses) {
		this.ingresoProductoses = ingresoProductoses;
	}

	public Set <OrdenPedido>getOrdenPedidos() {
		return this.ordenPedidos;
	}

	public void setOrdenPedidos(Set <OrdenPedido>ordenPedidos) {
		this.ordenPedidos = ordenPedidos;
	}

	public Set<OrdenProvisionInterna> getOrdenProvisionInternas() {
		return this.ordenProvisionInternas;
	}

	public void setOrdenProvisionInternas(Set<OrdenProvisionInterna> ordenProvisionInternas) {
		this.ordenProvisionInternas = ordenProvisionInternas;
	}

	public Set<OrdenTrabajoSectorTercero> getOrdenTrabajoSectorTerceros() {
		return this.ordenTrabajoSectorTerceros;
	}

	public void setOrdenTrabajoSectorTerceros(Set<OrdenTrabajoSectorTercero> ordenTrabajoSectorTerceros) {
		this.ordenTrabajoSectorTerceros = ordenTrabajoSectorTerceros;
	}

	public Set<IngresoInsumos> getIngresoInsumoses() {
		return this.ingresoInsumoses;
	}

	public void setIngresoInsumoses(Set <IngresoInsumos>ingresoInsumoses) {
		this.ingresoInsumoses = ingresoInsumoses;
	}

	public Set<RemitoInternoInsumo>getRemitoInternoInsumos() {
		return this.remitoInternoInsumos;
	}

	public void setRemitoInternoInsumos(Set <RemitoInternoInsumo>remitoInternoInsumos) {
		this.remitoInternoInsumos = remitoInternoInsumos;
	}

	public Set<OrdenCompraCotizacion>getOrdenCompraCotizacions() {
		return this.ordenCompraCotizacions;
	}

	public void setOrdenCompraCotizacions(Set <OrdenCompraCotizacion> ordenCompraCotizacions) {
		this.ordenCompraCotizacions = ordenCompraCotizacions;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set <Usuario>usuarios) {
		this.usuarios = usuarios;
	}

	public Set getEmpleadosForEmpleado() {
		return this.empleadosForEmpleado;
	}

	public void setEmpleadosForEmpleado(Set empleadosForEmpleado) {
		this.empleadosForEmpleado = empleadosForEmpleado;
	}

	public Set getOrdenProvisionInsumosForIdPedidoPara() {
		return this.ordenProvisionInsumosForIdPedidoPara;
	}

	public void setOrdenProvisionInsumosForIdPedidoPara(
			Set ordenProvisionInsumosForIdPedidoPara) {
		this.ordenProvisionInsumosForIdPedidoPara = ordenProvisionInsumosForIdPedidoPara;
	}

	public Set getOrdenProvisionInsumosForIdPedidoPor() {
		return this.ordenProvisionInsumosForIdPedidoPor;
	}

	public void setOrdenProvisionInsumosForIdPedidoPor(
			Set ordenProvisionInsumosForIdPedidoPor) {
		this.ordenProvisionInsumosForIdPedidoPor = ordenProvisionInsumosForIdPedidoPor;
	}

	public Set <OrdenFabricacionGeneral>getOrdenFabricacionGenerals() {
		return this.ordenFabricacionGenerals;
	}

	public void setOrdenFabricacionGenerals(Set <OrdenFabricacionGeneral> ordenFabricacionGenerals) {
		this.ordenFabricacionGenerals = ordenFabricacionGenerals;
	}

	public Set getEmpleadosForResponsable() {
		return this.empleadosForResponsable;
	}

	public void setEmpleadosForResponsable(Set empleadosForResponsable) {
		this.empleadosForResponsable = empleadosForResponsable;
	}

}
