package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6720316286876307623L;
	private int nroReferecncia;
	private SubclaseEquipo subclaseEquipo;
	private int idPatron;
	private int idMejora;
	private String descripcion;
	private String codigoBarras;
	private Set <RenglonOrdenPedido>renglonOrdenPedidos = new HashSet<RenglonOrdenPedido>(0);
	private Set <RenglonOrdenTrabajo>renglonOrdenTrabajos = new HashSet<RenglonOrdenTrabajo>(0);
	private Set <RenglonOrdenFabricacionGeneral>renglonOrdenFabricacionGenerals = new HashSet<RenglonOrdenFabricacionGeneral>(0);

	public Equipo() {
	}

	public Equipo(int nroReferecncia, SubclaseEquipo subclaseEquipo,
			int idPatron, int idMejora, String descripcion) {
		this.nroReferecncia = nroReferecncia;
		this.subclaseEquipo = subclaseEquipo;
		this.idPatron = idPatron;
		this.idMejora = idMejora;
		this.descripcion = descripcion;
	}

	public Equipo(int nroReferecncia, SubclaseEquipo subclaseEquipo,
			int idPatron, int idMejora, String descripcion,
			String codigoBarras, Set <RenglonOrdenPedido>renglonOrdenPedidos,
			Set <RenglonOrdenTrabajo>renglonOrdenTrabajos, Set<RenglonOrdenFabricacionGeneral> renglonOrdenFabricacionGenerals) {
		this.nroReferecncia = nroReferecncia;
		this.subclaseEquipo = subclaseEquipo;
		this.idPatron = idPatron;
		this.idMejora = idMejora;
		this.descripcion = descripcion;
		this.codigoBarras = codigoBarras;
		this.renglonOrdenPedidos = renglonOrdenPedidos;
		this.renglonOrdenTrabajos = renglonOrdenTrabajos;
		this.renglonOrdenFabricacionGenerals = renglonOrdenFabricacionGenerals;
	}

	public int getNroReferecncia() {
		return this.nroReferecncia;
	}

	public void setNroReferecncia(int nroReferecncia) {
		this.nroReferecncia = nroReferecncia;
	}

	public SubclaseEquipo getSubclaseEquipo() {
		return this.subclaseEquipo;
	}

	public void setSubclaseEquipo(SubclaseEquipo subclaseEquipo) {
		this.subclaseEquipo = subclaseEquipo;
	}

	public int getIdPatron() {
		return this.idPatron;
	}

	public void setIdPatron(int idPatron) {
		this.idPatron = idPatron;
	}

	public int getIdMejora() {
		return this.idMejora;
	}

	public void setIdMejora(int idMejora) {
		this.idMejora = idMejora;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(String codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	public Set <RenglonOrdenPedido>getRenglonOrdenPedidos() {
		return this.renglonOrdenPedidos;
	}

	public void setRenglonOrdenPedidos(Set <RenglonOrdenPedido>renglonOrdenPedidos) {
		this.renglonOrdenPedidos = renglonOrdenPedidos;
	}

	public Set<RenglonOrdenTrabajo> getRenglonOrdenTrabajos() {
		return this.renglonOrdenTrabajos;
	}

	public void setRenglonOrdenTrabajos(Set<RenglonOrdenTrabajo> renglonOrdenTrabajos) {
		this.renglonOrdenTrabajos = renglonOrdenTrabajos;
	}

	public Set<RenglonOrdenFabricacionGeneral> getRenglonOrdenFabricacionGenerals() {
		return this.renglonOrdenFabricacionGenerals;
	}

	public void setRenglonOrdenFabricacionGenerals(
			Set <RenglonOrdenFabricacionGeneral>renglonOrdenFabricacionGenerals) {
		this.renglonOrdenFabricacionGenerals = renglonOrdenFabricacionGenerals;
	}

}
