package edu.server.repositorio;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * IngresoInsumos generated by hbm2java
 */
public class IngresoInsumos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4740519195194860122L;
	private IngresoInsumosId id;
	private OrdenCompraInsumo ordenCompraInsumo;
	private Empleado empleado;
	private Date fechaIngreso;
	private String observaciones;
	private Set <RenglonIngresoInsumos>renglonIngresoInsumoses = new HashSet<RenglonIngresoInsumos>(0);

	public IngresoInsumos() {
	}

	public IngresoInsumos(IngresoInsumosId id,
			OrdenCompraInsumo ordenCompraInsumo, Empleado empleado,
			Date fechaIngreso) {
		this.id = id;
		this.ordenCompraInsumo = ordenCompraInsumo;
		this.empleado = empleado;
		this.fechaIngreso = fechaIngreso;
	}

	public IngresoInsumos(IngresoInsumosId id,
			OrdenCompraInsumo ordenCompraInsumo, Empleado empleado,
			Date fechaIngreso, String observaciones, Set <RenglonIngresoInsumos>renglonIngresoInsumoses) {
		this.id = id;
		this.ordenCompraInsumo = ordenCompraInsumo;
		this.empleado = empleado;
		this.fechaIngreso = fechaIngreso;
		this.observaciones = observaciones;
		this.renglonIngresoInsumoses = renglonIngresoInsumoses;
	}

	public IngresoInsumosId getId() {
		return this.id;
	}

	public void setId(IngresoInsumosId id) {
		this.id = id;
	}

	public OrdenCompraInsumo getOrdenCompraInsumo() {
		return this.ordenCompraInsumo;
	}

	public void setOrdenCompraInsumo(OrdenCompraInsumo ordenCompraInsumo) {
		this.ordenCompraInsumo = ordenCompraInsumo;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set<RenglonIngresoInsumos> getRenglonIngresoInsumoses() {
		return this.renglonIngresoInsumoses;
	}

	public void setRenglonIngresoInsumoses(Set <RenglonIngresoInsumos>renglonIngresoInsumoses) {
		this.renglonIngresoInsumoses = renglonIngresoInsumoses;
	}

}
