package edu.server.repositorio;


/**
 * IngresoInsumosId generated by hbm2java
 */
public class IngresoInsumosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 854078124644033350L;
	private long idOrdenCompraInsumos;
	private long nroRemitoExterno;

	public IngresoInsumosId() {
	}

	public IngresoInsumosId(long idOrdenCompraInsumos, long nroRemitoExterno) {
		this.idOrdenCompraInsumos = idOrdenCompraInsumos;
		this.nroRemitoExterno = nroRemitoExterno;
	}

	public long getIdOrdenCompraInsumos() {
		return this.idOrdenCompraInsumos;
	}

	public void setIdOrdenCompraInsumos(long idOrdenCompraInsumos) {
		this.idOrdenCompraInsumos = idOrdenCompraInsumos;
	}

	public long getNroRemitoExterno() {
		return this.nroRemitoExterno;
	}

	public void setNroRemitoExterno(long nroRemitoExterno) {
		this.nroRemitoExterno = nroRemitoExterno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IngresoInsumosId))
			return false;
		IngresoInsumosId castOther = (IngresoInsumosId) other;

		return (this.getIdOrdenCompraInsumos() == castOther
				.getIdOrdenCompraInsumos())
				&& (this.getNroRemitoExterno() == castOther
						.getNroRemitoExterno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdOrdenCompraInsumos();
		result = 37 * result + (int) this.getNroRemitoExterno();
		return result;
	}

}
