package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Insumo generated by hbm2java
 */
public class Insumo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1380117295675731968L;
	private int idInsumo;
	private Categoria categoria;
	private Marca marca;
	private String nombre;
	private String observaciones;
	private int cantidad;
	private int loteCompra;
	private int stockSeguridad;
	private boolean necesidadCompra;
	private Set <ProveedorDeInsumo>proveedorDeInsumos = new HashSet<ProveedorDeInsumo>(0);
	private Set <RenglonRemitoInternoInsumo>renglonRemitoInternoInsumos = new HashSet<RenglonRemitoInternoInsumo>(0);
	private Set <RenglonIngresoInsumos>renglonIngresoInsumoses = new HashSet<RenglonIngresoInsumos>(0);
	private Set <RenglonOrdenCompraInsumo>renglonOrdenCompraInsumos = new HashSet<RenglonOrdenCompraInsumo>(0);
	private Set <RenglonOrdenProvisionInsumo>renglonOrdenProvisionInsumos = new HashSet<RenglonOrdenProvisionInsumo>(0);

	public Insumo() {
	}

	public Insumo(int idInsumo, Categoria categoria, Marca marca,
			String nombre, int cantidad, int loteCompra, int stockSeguridad,
			boolean necesidadCompra) {
		this.idInsumo = idInsumo;
		this.categoria = categoria;
		this.marca = marca;
		this.nombre = nombre;
		this.cantidad = cantidad;
		this.loteCompra = loteCompra;
		this.stockSeguridad = stockSeguridad;
		this.necesidadCompra = necesidadCompra;
	}

	public Insumo(int idInsumo, Categoria categoria, Marca marca,
			String nombre, String observaciones, int cantidad, int loteCompra,
			int stockSeguridad, boolean necesidadCompra,
			Set <ProveedorDeInsumo>proveedorDeInsumos, Set <RenglonRemitoInternoInsumo>renglonRemitoInternoInsumos,
			Set <RenglonIngresoInsumos>renglonIngresoInsumoses, Set<RenglonOrdenCompraInsumo> renglonOrdenCompraInsumos,
			Set <RenglonOrdenProvisionInsumo>renglonOrdenProvisionInsumos) {
		this.idInsumo = idInsumo;
		this.categoria = categoria;
		this.marca = marca;
		this.nombre = nombre;
		this.observaciones = observaciones;
		this.cantidad = cantidad;
		this.loteCompra = loteCompra;
		this.stockSeguridad = stockSeguridad;
		this.necesidadCompra = necesidadCompra;
		this.proveedorDeInsumos = proveedorDeInsumos;
		this.renglonRemitoInternoInsumos = renglonRemitoInternoInsumos;
		this.renglonIngresoInsumoses = renglonIngresoInsumoses;
		this.renglonOrdenCompraInsumos = renglonOrdenCompraInsumos;
		this.renglonOrdenProvisionInsumos = renglonOrdenProvisionInsumos;
	}

	public int getIdInsumo() {
		return this.idInsumo;
	}

	public void setIdInsumo(int idInsumo) {
		this.idInsumo = idInsumo;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public int getLoteCompra() {
		return this.loteCompra;
	}

	public void setLoteCompra(int loteCompra) {
		this.loteCompra = loteCompra;
	}

	public int getStockSeguridad() {
		return this.stockSeguridad;
	}

	public void setStockSeguridad(int stockSeguridad) {
		this.stockSeguridad = stockSeguridad;
	}

	public boolean isNecesidadCompra() {
		return this.necesidadCompra;
	}

	public void setNecesidadCompra(boolean necesidadCompra) {
		this.necesidadCompra = necesidadCompra;
	}

	public Set <ProveedorDeInsumo>getProveedorDeInsumos() {
		return this.proveedorDeInsumos;
	}

	public void setProveedorDeInsumos(Set <ProveedorDeInsumo>proveedorDeInsumos) {
		this.proveedorDeInsumos = proveedorDeInsumos;
	}

	public Set <RenglonRemitoInternoInsumo>getRenglonRemitoInternoInsumos() {
		return this.renglonRemitoInternoInsumos;
	}

	public void setRenglonRemitoInternoInsumos(Set <RenglonRemitoInternoInsumo>renglonRemitoInternoInsumos) {
		this.renglonRemitoInternoInsumos = renglonRemitoInternoInsumos;
	}

	public Set<RenglonIngresoInsumos> getRenglonIngresoInsumoses() {
		return this.renglonIngresoInsumoses;
	}

	public void setRenglonIngresoInsumoses(Set<RenglonIngresoInsumos> renglonIngresoInsumoses) {
		this.renglonIngresoInsumoses = renglonIngresoInsumoses;
	}

	public Set<RenglonOrdenCompraInsumo> getRenglonOrdenCompraInsumos() {
		return this.renglonOrdenCompraInsumos;
	}

	public void setRenglonOrdenCompraInsumos(Set <RenglonOrdenCompraInsumo>renglonOrdenCompraInsumos) {
		this.renglonOrdenCompraInsumos = renglonOrdenCompraInsumos;
	}

	public Set <RenglonOrdenProvisionInsumo>getRenglonOrdenProvisionInsumos() {
		return this.renglonOrdenProvisionInsumos;
	}

	public void setRenglonOrdenProvisionInsumos(Set <RenglonOrdenProvisionInsumo>renglonOrdenProvisionInsumos) {
		this.renglonOrdenProvisionInsumos = renglonOrdenProvisionInsumos;
	}

}
