package edu.server.repositorio;

// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Inventario generated by hbm2java
 */
public class Inventario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7529994989492007894L;
	private int idInventario;
	private Producto producto;
	private int td;
	private String medida1;
	private String medida2;
	private double cantidadDisponible;
	private double cantDisponiblePendienteEntrega;
	private int loteCompra;
	private int stockSeguridad;
	private double porcentajeDefectuosos;
	private String codigoBarras;
	private Set <Reserva>reservas = new HashSet<Reserva>(0);

	public Inventario() {
	}

	public Inventario(int idInventario, Producto producto, int td,
			double cantidadDisponible, double cantDisponiblePendienteEntrega,
			int loteCompra, int stockSeguridad, double porcentajeDefectuosos) {
		this.idInventario = idInventario;
		this.producto = producto;
		this.td = td;
		this.cantidadDisponible = cantidadDisponible;
		this.cantDisponiblePendienteEntrega = cantDisponiblePendienteEntrega;
		this.loteCompra = loteCompra;
		this.stockSeguridad = stockSeguridad;
		this.porcentajeDefectuosos = porcentajeDefectuosos;
	}

	public Inventario(int idInventario, Producto producto, int td,
			String medida1, String medida2, double cantidadDisponible,
			double cantDisponiblePendienteEntrega, int loteCompra,
			int stockSeguridad, double porcentajeDefectuosos,
			String codigoBarras, Set <Reserva>reservas) {
		this.idInventario = idInventario;
		this.producto = producto;
		this.td = td;
		this.medida1 = medida1;
		this.medida2 = medida2;
		this.cantidadDisponible = cantidadDisponible;
		this.cantDisponiblePendienteEntrega = cantDisponiblePendienteEntrega;
		this.loteCompra = loteCompra;
		this.stockSeguridad = stockSeguridad;
		this.porcentajeDefectuosos = porcentajeDefectuosos;
		this.codigoBarras = codigoBarras;
		this.reservas = reservas;
	}

	public int getIdInventario() {
		return this.idInventario;
	}

	public void setIdInventario(int idInventario) {
		this.idInventario = idInventario;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public int getTd() {
		return this.td;
	}

	public void setTd(int td) {
		this.td = td;
	}

	public String getMedida1() {
		return this.medida1;
	}

	public void setMedida1(String medida1) {
		this.medida1 = medida1;
	}

	public String getMedida2() {
		return this.medida2;
	}

	public void setMedida2(String medida2) {
		this.medida2 = medida2;
	}

	public double getCantidadDisponible() {
		return this.cantidadDisponible;
	}

	public void setCantidadDisponible(double cantidadDisponible) {
		this.cantidadDisponible = cantidadDisponible;
	}

	public double getCantDisponiblePendienteEntrega() {
		return this.cantDisponiblePendienteEntrega;
	}

	public void setCantDisponiblePendienteEntrega(
			double cantDisponiblePendienteEntrega) {
		this.cantDisponiblePendienteEntrega = cantDisponiblePendienteEntrega;
	}

	public int getLoteCompra() {
		return this.loteCompra;
	}

	public void setLoteCompra(int loteCompra) {
		this.loteCompra = loteCompra;
	}

	public int getStockSeguridad() {
		return this.stockSeguridad;
	}

	public void setStockSeguridad(int stockSeguridad) {
		this.stockSeguridad = stockSeguridad;
	}

	public double getPorcentajeDefectuosos() {
		return this.porcentajeDefectuosos;
	}

	public void setPorcentajeDefectuosos(double porcentajeDefectuosos) {
		this.porcentajeDefectuosos = porcentajeDefectuosos;
	}

	public String getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(String codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

}
