package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * ListaDeMateriales generated by hbm2java
 */
public class ListaDeMateriales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5106009514573931974L;
	private int idListaDeMateriales;
	private Plano plano;
	private Integer nroReferencia;
	private Integer idComponente;
	private Set <RenglonListaDeMateriales>renglonListaDeMaterialeses = new HashSet<RenglonListaDeMateriales>(0);

	public ListaDeMateriales() {
	}

	public ListaDeMateriales(int idListaDeMateriales, Plano plano) {
		this.idListaDeMateriales = idListaDeMateriales;
		this.plano = plano;
	}

	public ListaDeMateriales(int idListaDeMateriales, Plano plano,
			Integer nroReferencia, Integer idComponente,
			Set <RenglonListaDeMateriales>renglonListaDeMaterialeses) {
		this.idListaDeMateriales = idListaDeMateriales;
		this.plano = plano;
		this.nroReferencia = nroReferencia;
		this.idComponente = idComponente;
		this.renglonListaDeMaterialeses = renglonListaDeMaterialeses;
	}

	public int getIdListaDeMateriales() {
		return this.idListaDeMateriales;
	}

	public void setIdListaDeMateriales(int idListaDeMateriales) {
		this.idListaDeMateriales = idListaDeMateriales;
	}

	public Plano getPlano() {
		return this.plano;
	}

	public void setPlano(Plano plano) {
		this.plano = plano;
	}

	public Integer getNroReferencia() {
		return this.nroReferencia;
	}

	public void setNroReferencia(Integer nroReferencia) {
		this.nroReferencia = nroReferencia;
	}

	public Integer getIdComponente() {
		return this.idComponente;
	}

	public void setIdComponente(Integer idComponente) {
		this.idComponente = idComponente;
	}

	public Set<RenglonListaDeMateriales> getRenglonListaDeMaterialeses() {
		return this.renglonListaDeMaterialeses;
	}

	public void setRenglonListaDeMaterialeses(Set<RenglonListaDeMateriales> renglonListaDeMaterialeses) {
		this.renglonListaDeMaterialeses = renglonListaDeMaterialeses;
	}

}
