package edu.server.repositorio;


// Generated 20-oct-2012 16:37:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ListaDeMateriales generated by hbm2java
 */
public class ListaDeMateriales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 926424970389187282L;
	private int idListaDeMateriales;
	private Plano plano;
	private Componente componente;
	private Equipo equipo;
	private Set<RenglonListaDeMateriales> renglonListaDeMaterialeses = new HashSet<RenglonListaDeMateriales>(0);

	public ListaDeMateriales() {
	}

	public ListaDeMateriales(int idListaDeMateriales, Plano plano) {
		this.idListaDeMateriales = idListaDeMateriales;
		this.plano = plano;
	}

	public ListaDeMateriales(int idListaDeMateriales, Plano plano,
			Componente componente, Equipo equipo, Set<RenglonListaDeMateriales> renglonListaDeMaterialeses) {
		this.idListaDeMateriales = idListaDeMateriales;
		this.plano = plano;
		this.componente = componente;
		this.equipo = equipo;
		this.renglonListaDeMaterialeses = renglonListaDeMaterialeses;
	}

	public int getIdListaDeMateriales() {
		return this.idListaDeMateriales;
	}

	public void setIdListaDeMateriales(int idListaDeMateriales) {
		this.idListaDeMateriales = idListaDeMateriales;
	}

	public Plano getPlano() {
		return this.plano;
	}

	public void setPlano(Plano plano) {
		this.plano = plano;
	}

	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public Set<RenglonListaDeMateriales> getRenglonListaDeMaterialeses() {
		return this.renglonListaDeMaterialeses;
	}

	public void setRenglonListaDeMaterialeses(Set<RenglonListaDeMateriales> renglonListaDeMaterialeses) {
		this.renglonListaDeMaterialeses = renglonListaDeMaterialeses;
	}

}
