package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8186425771016716764L;
	private int idLocalidad;
	private Provincia provincia;
	private String nombre;
	private String codigoPostal;
	private Set <Direccion>direccions = new HashSet<Direccion>(0);

	public Localidad() {
	}

	public Localidad(int idLocalidad, Provincia provincia, String nombre) {
		this.idLocalidad = idLocalidad;
		this.provincia = provincia;
		this.nombre = nombre;
	}

	public Localidad(int idLocalidad, Provincia provincia, String nombre,
			String codigoPostal, Set<Direccion> direccions) {
		this.idLocalidad = idLocalidad;
		this.provincia = provincia;
		this.nombre = nombre;
		this.codigoPostal = codigoPostal;
		this.direccions = direccions;
	}

	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

}
