package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Maquina generated by hbm2java
 */
public class Maquina implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5879297654458148850L;
	private int idMaquina;
	private String descripcion;
	private Set <Proveedor>proveedors = new HashSet<Proveedor>(0);

	public Maquina() {
	}

	public Maquina(int idMaquina, String descripcion) {
		this.idMaquina = idMaquina;
		this.descripcion = descripcion;
	}

	public Maquina(int idMaquina, String descripcion, Set<Proveedor> proveedors) {
		this.idMaquina = idMaquina;
		this.descripcion = descripcion;
		this.proveedors = proveedors;
	}

	public int getIdMaquina() {
		return this.idMaquina;
	}

	public void setIdMaquina(int idMaquina) {
		this.idMaquina = idMaquina;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Proveedor> getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set <Proveedor>proveedors) {
		this.proveedors = proveedors;
	}

}
