package edu.server.repositorio;

// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7134965290469524636L;
	private String idMaterial;
	private String nombre;
	private double pesoEspecifico;
	private Set<CodigoProducto> codigoProductos = new HashSet<CodigoProducto>(0);

	public Material() {
	}

	public Material(String idMaterial, String nombre, double pesoEspecifico) {
		this.idMaterial = idMaterial;
		this.nombre = nombre;
		this.pesoEspecifico = pesoEspecifico;
	}

	public Material(String idMaterial, String nombre, double pesoEspecifico,
			Set <CodigoProducto>codigoProductos) {
		this.idMaterial = idMaterial;
		this.nombre = nombre;
		this.pesoEspecifico = pesoEspecifico;
		this.codigoProductos = codigoProductos;
	}

	public String getIdMaterial() {
		return this.idMaterial;
	}

	public void setIdMaterial(String idMaterial) {
		this.idMaterial = idMaterial;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getPesoEspecifico() {
		return this.pesoEspecifico;
	}

	public void setPesoEspecifico(double pesoEspecifico) {
		this.pesoEspecifico = pesoEspecifico;
	}

	public Set <CodigoProducto>getCodigoProductos() {
		return this.codigoProductos;
	}

	public void setCodigoProductos(Set<CodigoProducto> codigoProductos) {
		this.codigoProductos = codigoProductos;
	}

}
