package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * ModoEnvio generated by hbm2java
 */
public class ModoEnvio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -593943358148123129L;
	private int idModoEnvio;
	private String descripcion;
	private Set<OrdenCompraCotizacion> ordenCompraCotizacions = new HashSet<OrdenCompraCotizacion>(0);
	private Set<OrdenCompraInsumo> ordenCompraInsumos = new HashSet<OrdenCompraInsumo>(0);

	public ModoEnvio() {
	}

	public ModoEnvio(int idModoEnvio, String descripcion) {
		this.idModoEnvio = idModoEnvio;
		this.descripcion = descripcion;
	}

	public ModoEnvio(int idModoEnvio, String descripcion,
			Set <OrdenCompraCotizacion>ordenCompraCotizacions, Set <OrdenCompraInsumo>ordenCompraInsumos) {
		this.idModoEnvio = idModoEnvio;
		this.descripcion = descripcion;
		this.ordenCompraCotizacions = ordenCompraCotizacions;
		this.ordenCompraInsumos = ordenCompraInsumos;
	}

	public int getIdModoEnvio() {
		return this.idModoEnvio;
	}

	public void setIdModoEnvio(int idModoEnvio) {
		this.idModoEnvio = idModoEnvio;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<OrdenCompraCotizacion> getOrdenCompraCotizacions() {
		return this.ordenCompraCotizacions;
	}

	public void setOrdenCompraCotizacions(Set<OrdenCompraCotizacion> ordenCompraCotizacions) {
		this.ordenCompraCotizacions = ordenCompraCotizacions;
	}

	public Set<OrdenCompraInsumo> getOrdenCompraInsumos() {
		return this.ordenCompraInsumos;
	}

	public void setOrdenCompraInsumos(Set<OrdenCompraInsumo> ordenCompraInsumos) {
		this.ordenCompraInsumos = ordenCompraInsumos;
	}

}
