package edu.server.repositorio;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenCompraInsumo generated by hbm2java
 */
public class OrdenCompraInsumo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3890504187676064146L;
	private long nroOrdenCompraInsumo;
	private Empleado empleado;
	private Proveedor proveedor;
	private ModoEnvio modoEnvio;
	private EstadoOrden estadoOrden;
	private Date fechaEdicion;
	private Date fechaGeneracion;
	private Date fechaCierre;
	private String formaPago;
	private Double iva;
	private Double total;
	private String observaciones;
	private Set <RenglonOrdenCompraInsumo>renglonOrdenCompraInsumos = new HashSet<RenglonOrdenCompraInsumo>(0);
	private Set <IngresoInsumos>ingresoInsumoses = new HashSet<IngresoInsumos>(0);

	public OrdenCompraInsumo() {
	}

	public OrdenCompraInsumo(long nroOrdenCompraInsumo, Empleado empleado,
			Proveedor proveedor, EstadoOrden estadoOrden, Date fechaEdicion) {
		this.nroOrdenCompraInsumo = nroOrdenCompraInsumo;
		this.empleado = empleado;
		this.proveedor = proveedor;
		this.estadoOrden = estadoOrden;
		this.fechaEdicion = fechaEdicion;
	}

	public OrdenCompraInsumo(long nroOrdenCompraInsumo, Empleado empleado,
			Proveedor proveedor, ModoEnvio modoEnvio, EstadoOrden estadoOrden,
			Date fechaEdicion, Date fechaGeneracion, Date fechaCierre,
			String formaPago, Double iva, Double total, String observaciones,
			Set <RenglonOrdenCompraInsumo>renglonOrdenCompraInsumos, Set <IngresoInsumos>ingresoInsumoses) {
		this.nroOrdenCompraInsumo = nroOrdenCompraInsumo;
		this.empleado = empleado;
		this.proveedor = proveedor;
		this.modoEnvio = modoEnvio;
		this.estadoOrden = estadoOrden;
		this.fechaEdicion = fechaEdicion;
		this.fechaGeneracion = fechaGeneracion;
		this.fechaCierre = fechaCierre;
		this.formaPago = formaPago;
		this.iva = iva;
		this.total = total;
		this.observaciones = observaciones;
		this.renglonOrdenCompraInsumos = renglonOrdenCompraInsumos;
		this.ingresoInsumoses = ingresoInsumoses;
	}

	public long getNroOrdenCompraInsumo() {
		return this.nroOrdenCompraInsumo;
	}

	public void setNroOrdenCompraInsumo(long nroOrdenCompraInsumo) {
		this.nroOrdenCompraInsumo = nroOrdenCompraInsumo;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public ModoEnvio getModoEnvio() {
		return this.modoEnvio;
	}

	public void setModoEnvio(ModoEnvio modoEnvio) {
		this.modoEnvio = modoEnvio;
	}

	public EstadoOrden getEstadoOrden() {
		return this.estadoOrden;
	}

	public void setEstadoOrden(EstadoOrden estadoOrden) {
		this.estadoOrden = estadoOrden;
	}

	public Date getFechaEdicion() {
		return this.fechaEdicion;
	}

	public void setFechaEdicion(Date fechaEdicion) {
		this.fechaEdicion = fechaEdicion;
	}

	public Date getFechaGeneracion() {
		return this.fechaGeneracion;
	}

	public void setFechaGeneracion(Date fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}

	public Double getIva() {
		return this.iva;
	}

	public void setIva(Double iva) {
		this.iva = iva;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set<RenglonOrdenCompraInsumo> getRenglonOrdenCompraInsumos() {
		return this.renglonOrdenCompraInsumos;
	}

	public void setRenglonOrdenCompraInsumos(Set <RenglonOrdenCompraInsumo>renglonOrdenCompraInsumos) {
		this.renglonOrdenCompraInsumos = renglonOrdenCompraInsumos;
	}

	public Set<IngresoInsumos> getIngresoInsumoses() {
		return this.ingresoInsumoses;
	}

	public void setIngresoInsumoses(Set<IngresoInsumos> ingresoInsumoses) {
		this.ingresoInsumoses = ingresoInsumoses;
	}

}
