package edu.server.repositorio;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenFabricacionGeneral generated by hbm2java
 */
public class OrdenFabricacionGeneral implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1537355632667408745L;
	private long nroOrden;
	private OrdenPedido ordenPedido;
	private EstadoOrden estadoOrden;
	private Empleado empleado;
	private Date fechaEdicion;
	private Date fechaGeneracion;
	private Date fechaCierre;
	private Date fechaPrevistaFinalizacion;
	private String observaciones;
	private Set <ReservaComponente>reservaComponentes = new HashSet<ReservaComponente>(0);
	private Set <RenglonOrdenFabricacionGeneral>renglonOrdenFabricacionGenerals = new HashSet<RenglonOrdenFabricacionGeneral>(0);
	private Set <Reserva>reservas = new HashSet<Reserva>(0);
	private Set <RequerimientoMateriales>requerimientoMaterialeses = new HashSet<RequerimientoMateriales>(0);
	private Set <OrdenCompraCotizacion>ordenCompraCotizacions = new HashSet<OrdenCompraCotizacion>(0);
	private Set <OrdenTrabajoSectorTercero>ordenTrabajoSectorTerceros = new HashSet<OrdenTrabajoSectorTercero>(0);

	public OrdenFabricacionGeneral() {
	}

	public OrdenFabricacionGeneral(long nroOrden, EstadoOrden estadoOrden,
			Empleado empleado, Date fechaEdicion) {
		this.nroOrden = nroOrden;
		this.estadoOrden = estadoOrden;
		this.empleado = empleado;
		this.fechaEdicion = fechaEdicion;
	}

	public OrdenFabricacionGeneral(long nroOrden, OrdenPedido ordenPedido,
			EstadoOrden estadoOrden, Empleado empleado, Date fechaEdicion,
			Date fechaGeneracion, Date fechaCierre,
			Date fechaPrevistaFinalizacion, String observaciones,
			Set <ReservaComponente>reservaComponentes, Set <RenglonOrdenFabricacionGeneral>renglonOrdenFabricacionGenerals,
			Set <Reserva>reservas, Set <RequerimientoMateriales>requerimientoMaterialeses,
			Set <OrdenCompraCotizacion>ordenCompraCotizacions, Set <OrdenTrabajoSectorTercero>ordenTrabajoSectorTerceros) {
		this.nroOrden = nroOrden;
		this.ordenPedido = ordenPedido;
		this.estadoOrden = estadoOrden;
		this.empleado = empleado;
		this.fechaEdicion = fechaEdicion;
		this.fechaGeneracion = fechaGeneracion;
		this.fechaCierre = fechaCierre;
		this.fechaPrevistaFinalizacion = fechaPrevistaFinalizacion;
		this.observaciones = observaciones;
		this.reservaComponentes = reservaComponentes;
		this.renglonOrdenFabricacionGenerals = renglonOrdenFabricacionGenerals;
		this.reservas = reservas;
		this.requerimientoMaterialeses = requerimientoMaterialeses;
		this.ordenCompraCotizacions = ordenCompraCotizacions;
		this.ordenTrabajoSectorTerceros = ordenTrabajoSectorTerceros;
	}

	public long getNroOrden() {
		return this.nroOrden;
	}

	public void setNroOrden(long nroOrden) {
		this.nroOrden = nroOrden;
	}

	public OrdenPedido getOrdenPedido() {
		return this.ordenPedido;
	}

	public void setOrdenPedido(OrdenPedido ordenPedido) {
		this.ordenPedido = ordenPedido;
	}

	public EstadoOrden getEstadoOrden() {
		return this.estadoOrden;
	}

	public void setEstadoOrden(EstadoOrden estadoOrden) {
		this.estadoOrden = estadoOrden;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Date getFechaEdicion() {
		return this.fechaEdicion;
	}

	public void setFechaEdicion(Date fechaEdicion) {
		this.fechaEdicion = fechaEdicion;
	}

	public Date getFechaGeneracion() {
		return this.fechaGeneracion;
	}

	public void setFechaGeneracion(Date fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public Date getFechaPrevistaFinalizacion() {
		return this.fechaPrevistaFinalizacion;
	}

	public void setFechaPrevistaFinalizacion(Date fechaPrevistaFinalizacion) {
		this.fechaPrevistaFinalizacion = fechaPrevistaFinalizacion;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set<ReservaComponente> getReservaComponentes() {
		return this.reservaComponentes;
	}

	public void setReservaComponentes(Set<ReservaComponente> reservaComponentes) {
		this.reservaComponentes = reservaComponentes;
	}

	public Set <RenglonOrdenFabricacionGeneral>getRenglonOrdenFabricacionGenerals() {
		return this.renglonOrdenFabricacionGenerals;
	}

	public void setRenglonOrdenFabricacionGenerals(
			Set<RenglonOrdenFabricacionGeneral> renglonOrdenFabricacionGenerals) {
		this.renglonOrdenFabricacionGenerals = renglonOrdenFabricacionGenerals;
	}

	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set <Reserva>reservas) {
		this.reservas = reservas;
	}

	public Set<RequerimientoMateriales> getRequerimientoMaterialeses() {
		return this.requerimientoMaterialeses;
	}

	public void setRequerimientoMaterialeses(Set<RequerimientoMateriales> requerimientoMaterialeses) {
		this.requerimientoMaterialeses = requerimientoMaterialeses;
	}

	public Set <OrdenCompraCotizacion>getOrdenCompraCotizacions() {
		return this.ordenCompraCotizacions;
	}

	public void setOrdenCompraCotizacions(Set <OrdenCompraCotizacion>ordenCompraCotizacions) {
		this.ordenCompraCotizacions = ordenCompraCotizacions;
	}

	public Set<OrdenTrabajoSectorTercero> getOrdenTrabajoSectorTerceros() {
		return this.ordenTrabajoSectorTerceros;
	}

	public void setOrdenTrabajoSectorTerceros(Set <OrdenTrabajoSectorTercero>ordenTrabajoSectorTerceros) {
		this.ordenTrabajoSectorTerceros = ordenTrabajoSectorTerceros;
	}

}
