package edu.server.repositorio;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenTrabajoSectorTercero generated by hbm2java
 */
public class OrdenTrabajoSectorTercero implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5195357290855925538L;
	private long idOrdenTrabajo;
	private OrdenFabricacionGeneral ordenFabricacionGeneral;
	private Empleado empleado;
	private Proveedor proveedor;
	private EstadoOrden estadoOrden;
	private boolean sectorTercero;
	private Date fechaEdicion;
	private Date fechaGeneracion;
	private Date fechaCierre;
	private Set <RenglonOrdenTrabajo>renglonOrdenTrabajos = new HashSet<RenglonOrdenTrabajo>(0);

	public OrdenTrabajoSectorTercero() {
	}

	public OrdenTrabajoSectorTercero(long idOrdenTrabajo,
			OrdenFabricacionGeneral ordenFabricacionGeneral,
			EstadoOrden estadoOrden, boolean sectorTercero, Date fechaEdicion) {
		this.idOrdenTrabajo = idOrdenTrabajo;
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
		this.estadoOrden = estadoOrden;
		this.sectorTercero = sectorTercero;
		this.fechaEdicion = fechaEdicion;
	}

	public OrdenTrabajoSectorTercero(long idOrdenTrabajo,
			OrdenFabricacionGeneral ordenFabricacionGeneral, Empleado empleado,
			Proveedor proveedor, EstadoOrden estadoOrden,
			boolean sectorTercero, Date fechaEdicion, Date fechaGeneracion,
			Date fechaCierre, Set<RenglonOrdenTrabajo> renglonOrdenTrabajos) {
		this.idOrdenTrabajo = idOrdenTrabajo;
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
		this.empleado = empleado;
		this.proveedor = proveedor;
		this.estadoOrden = estadoOrden;
		this.sectorTercero = sectorTercero;
		this.fechaEdicion = fechaEdicion;
		this.fechaGeneracion = fechaGeneracion;
		this.fechaCierre = fechaCierre;
		this.renglonOrdenTrabajos = renglonOrdenTrabajos;
	}

	public long getIdOrdenTrabajo() {
		return this.idOrdenTrabajo;
	}

	public void setIdOrdenTrabajo(long idOrdenTrabajo) {
		this.idOrdenTrabajo = idOrdenTrabajo;
	}

	public OrdenFabricacionGeneral getOrdenFabricacionGeneral() {
		return this.ordenFabricacionGeneral;
	}

	public void setOrdenFabricacionGeneral(
			OrdenFabricacionGeneral ordenFabricacionGeneral) {
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public EstadoOrden getEstadoOrden() {
		return this.estadoOrden;
	}

	public void setEstadoOrden(EstadoOrden estadoOrden) {
		this.estadoOrden = estadoOrden;
	}

	public boolean isSectorTercero() {
		return this.sectorTercero;
	}

	public void setSectorTercero(boolean sectorTercero) {
		this.sectorTercero = sectorTercero;
	}

	public Date getFechaEdicion() {
		return this.fechaEdicion;
	}

	public void setFechaEdicion(Date fechaEdicion) {
		this.fechaEdicion = fechaEdicion;
	}

	public Date getFechaGeneracion() {
		return this.fechaGeneracion;
	}

	public void setFechaGeneracion(Date fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public Set<RenglonOrdenTrabajo> getRenglonOrdenTrabajos() {
		return this.renglonOrdenTrabajos;
	}

	public void setRenglonOrdenTrabajos(Set <RenglonOrdenTrabajo>renglonOrdenTrabajos) {
		this.renglonOrdenTrabajos = renglonOrdenTrabajos;
	}

}
