package edu.server.repositorio;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenProvisionInsumo generated by hbm2java
 */
public class OrdenProvisionInsumo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4130470221095987790L;
	private long idOrdenProvisionInsumo;
	private Empleado empleadoByIdPedidoPara;
	private Empleado empleadoByIdPedidoPor;
	private EstadoOrden estadoOrden;
	private Date fechaEdicion;
	private Date fechaGeneracion;
	private Date fechaCierre;
	private String observaciones;
	private Set <RemitoInternoInsumo>remitoInternoInsumos = new HashSet<RemitoInternoInsumo>(0);
	private Set <RenglonOrdenProvisionInsumo>renglonOrdenProvisionInsumos = new HashSet<RenglonOrdenProvisionInsumo>(0);

	public OrdenProvisionInsumo() {
	}

	public OrdenProvisionInsumo(long idOrdenProvisionInsumo,
			Empleado empleadoByIdPedidoPara, Empleado empleadoByIdPedidoPor,
			EstadoOrden estadoOrden, Date fechaEdicion) {
		this.idOrdenProvisionInsumo = idOrdenProvisionInsumo;
		this.empleadoByIdPedidoPara = empleadoByIdPedidoPara;
		this.empleadoByIdPedidoPor = empleadoByIdPedidoPor;
		this.estadoOrden = estadoOrden;
		this.fechaEdicion = fechaEdicion;
	}

	public OrdenProvisionInsumo(long idOrdenProvisionInsumo,
			Empleado empleadoByIdPedidoPara, Empleado empleadoByIdPedidoPor,
			EstadoOrden estadoOrden, Date fechaEdicion, Date fechaGeneracion,
			Date fechaCierre, String observaciones, Set<RemitoInternoInsumo> remitoInternoInsumos,
			Set<RenglonOrdenProvisionInsumo> renglonOrdenProvisionInsumos) {
		this.idOrdenProvisionInsumo = idOrdenProvisionInsumo;
		this.empleadoByIdPedidoPara = empleadoByIdPedidoPara;
		this.empleadoByIdPedidoPor = empleadoByIdPedidoPor;
		this.estadoOrden = estadoOrden;
		this.fechaEdicion = fechaEdicion;
		this.fechaGeneracion = fechaGeneracion;
		this.fechaCierre = fechaCierre;
		this.observaciones = observaciones;
		this.remitoInternoInsumos = remitoInternoInsumos;
		this.renglonOrdenProvisionInsumos = renglonOrdenProvisionInsumos;
	}

	public long getIdOrdenProvisionInsumo() {
		return this.idOrdenProvisionInsumo;
	}

	public void setIdOrdenProvisionInsumo(long idOrdenProvisionInsumo) {
		this.idOrdenProvisionInsumo = idOrdenProvisionInsumo;
	}

	public Empleado getEmpleadoByIdPedidoPara() {
		return this.empleadoByIdPedidoPara;
	}

	public void setEmpleadoByIdPedidoPara(Empleado empleadoByIdPedidoPara) {
		this.empleadoByIdPedidoPara = empleadoByIdPedidoPara;
	}

	public Empleado getEmpleadoByIdPedidoPor() {
		return this.empleadoByIdPedidoPor;
	}

	public void setEmpleadoByIdPedidoPor(Empleado empleadoByIdPedidoPor) {
		this.empleadoByIdPedidoPor = empleadoByIdPedidoPor;
	}

	public EstadoOrden getEstadoOrden() {
		return this.estadoOrden;
	}

	public void setEstadoOrden(EstadoOrden estadoOrden) {
		this.estadoOrden = estadoOrden;
	}

	public Date getFechaEdicion() {
		return this.fechaEdicion;
	}

	public void setFechaEdicion(Date fechaEdicion) {
		this.fechaEdicion = fechaEdicion;
	}

	public Date getFechaGeneracion() {
		return this.fechaGeneracion;
	}

	public void setFechaGeneracion(Date fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set<RemitoInternoInsumo>getRemitoInternoInsumos() {
		return this.remitoInternoInsumos;
	}

	public void setRemitoInternoInsumos(Set <RemitoInternoInsumo>remitoInternoInsumos) {
		this.remitoInternoInsumos = remitoInternoInsumos;
	}

	public Set<RenglonOrdenProvisionInsumo>getRenglonOrdenProvisionInsumos() {
		return this.renglonOrdenProvisionInsumos;
	}

	public void setRenglonOrdenProvisionInsumos(Set <RenglonOrdenProvisionInsumo>renglonOrdenProvisionInsumos) {
		this.renglonOrdenProvisionInsumos = renglonOrdenProvisionInsumos;
	}

}
