package edu.server.repositorio;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenPedido generated by hbm2java
 */
public class OrdenPedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1043432218920325277L;
	private long nroOrden;
	private EstadoOrden estadoOrden;
	private Cliente cliente;
	private Empleado empleado;
	private Date fechaEdicion;
	private Date fechaGeneracion;
	private Date fechaCierre;
	private Date fechaPrevistaEntrega;
	private boolean planificada;
	private String ordenCompra;
	private String presupuesto;
	private String observacion;
	private Set <RenglonOrdenPedido>renglonOrdenPedidos = new HashSet<RenglonOrdenPedido>(0);
	private Set <OrdenFabricacionGeneral>ordenFabricacionGenerals = new HashSet<OrdenFabricacionGeneral>(0);

	public OrdenPedido() {
	}

	public OrdenPedido(long nroOrden, EstadoOrden estadoOrden,
			Empleado empleado, Date fechaEdicion, boolean planificada) {
		this.nroOrden = nroOrden;
		this.estadoOrden = estadoOrden;
		this.empleado = empleado;
		this.fechaEdicion = fechaEdicion;
		this.planificada = planificada;
	}

	public OrdenPedido(long nroOrden, EstadoOrden estadoOrden, Cliente cliente,
			Empleado empleado, Date fechaEdicion, Date fechaGeneracion,
			Date fechaCierre, Date fechaPrevistaEntrega, boolean planificada,
			String ordenCompra, String presupuesto, String observacion,
			Set<RenglonOrdenPedido> renglonOrdenPedidos, Set<OrdenFabricacionGeneral> ordenFabricacionGenerals) {
		this.nroOrden = nroOrden;
		this.estadoOrden = estadoOrden;
		this.cliente = cliente;
		this.empleado = empleado;
		this.fechaEdicion = fechaEdicion;
		this.fechaGeneracion = fechaGeneracion;
		this.fechaCierre = fechaCierre;
		this.fechaPrevistaEntrega = fechaPrevistaEntrega;
		this.planificada = planificada;
		this.ordenCompra = ordenCompra;
		this.presupuesto = presupuesto;
		this.observacion = observacion;
		this.renglonOrdenPedidos = renglonOrdenPedidos;
		this.ordenFabricacionGenerals = ordenFabricacionGenerals;
	}

	public long getNroOrden() {
		return this.nroOrden;
	}

	public void setNroOrden(long nroOrden) {
		this.nroOrden = nroOrden;
	}

	public EstadoOrden getEstadoOrden() {
		return this.estadoOrden;
	}

	public void setEstadoOrden(EstadoOrden estadoOrden) {
		this.estadoOrden = estadoOrden;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Date getFechaEdicion() {
		return this.fechaEdicion;
	}

	public void setFechaEdicion(Date fechaEdicion) {
		this.fechaEdicion = fechaEdicion;
	}

	public Date getFechaGeneracion() {
		return this.fechaGeneracion;
	}

	public void setFechaGeneracion(Date fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public Date getFechaPrevistaEntrega() {
		return this.fechaPrevistaEntrega;
	}

	public void setFechaPrevistaEntrega(Date fechaPrevistaEntrega) {
		this.fechaPrevistaEntrega = fechaPrevistaEntrega;
	}

	public boolean isPlanificada() {
		return this.planificada;
	}

	public void setPlanificada(boolean planificada) {
		this.planificada = planificada;
	}

	public String getOrdenCompra() {
		return this.ordenCompra;
	}

	public void setOrdenCompra(String ordenCompra) {
		this.ordenCompra = ordenCompra;
	}

	public String getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(String presupuesto) {
		this.presupuesto = presupuesto;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Set<RenglonOrdenPedido> getRenglonOrdenPedidos() {
		return this.renglonOrdenPedidos;
	}

	public void setRenglonOrdenPedidos(Set<RenglonOrdenPedido> renglonOrdenPedidos) {
		this.renglonOrdenPedidos = renglonOrdenPedidos;
	}

	public Set <OrdenFabricacionGeneral>getOrdenFabricacionGenerals() {
		return this.ordenFabricacionGenerals;
	}

	public void setOrdenFabricacionGenerals(Set<OrdenFabricacionGeneral>ordenFabricacionGenerals) {
		this.ordenFabricacionGenerals = ordenFabricacionGenerals;
	}

}
