package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6201553135589649198L;
	private int idPais;
	private String nombre;
	private Set <Provincia> provincias = new HashSet<Provincia>(0);

	public Pais() {
	}

	public Pais(int idPais, String nombre) {
		this.idPais = idPais;
		this.nombre = nombre;
	}

	public Pais(int idPais, String nombre, Set <Provincia>provincias) {
		this.idPais = idPais;
		this.nombre = nombre;
		this.provincias = provincias;
	}

	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Provincia> getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Set<Provincia> provincias) {
		this.provincias = provincias;
	}

}
