package edu.server.repositorio;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Plano generated by hbm2java
 */
public class Plano implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7264141948680191970L;
	private int idPlano;
	private String codigo;
	private Date remplazadoPor;
	private Date remplazaA;
	private Date fecha;
	private Set <ListaDeMateriales> listaDeMaterialeses = new HashSet<ListaDeMateriales>(0);

	public Plano() {
	}

	public Plano(int idPlano, String codigo, Date fecha) {
		this.idPlano = idPlano;
		this.codigo = codigo;
		this.fecha = fecha;
	}

	public Plano(int idPlano, String codigo, Date remplazadoPor,
			Date remplazaA, Date fecha, Set<ListaDeMateriales> listaDeMaterialeses) {
		this.idPlano = idPlano;
		this.codigo = codigo;
		this.remplazadoPor = remplazadoPor;
		this.remplazaA = remplazaA;
		this.fecha = fecha;
		this.listaDeMaterialeses = listaDeMaterialeses;
	}

	public int getIdPlano() {
		return this.idPlano;
	}

	public void setIdPlano(int idPlano) {
		this.idPlano = idPlano;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Date getRemplazadoPor() {
		return this.remplazadoPor;
	}

	public void setRemplazadoPor(Date remplazadoPor) {
		this.remplazadoPor = remplazadoPor;
	}

	public Date getRemplazaA() {
		return this.remplazaA;
	}

	public void setRemplazaA(Date remplazaA) {
		this.remplazaA = remplazaA;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set<ListaDeMateriales> getListaDeMaterialeses() {
		return this.listaDeMaterialeses;
	}

	public void setListaDeMaterialeses(Set<ListaDeMateriales> listaDeMaterialeses) {
		this.listaDeMaterialeses = listaDeMaterialeses;
	}

}
