package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1697817723082653769L;
	private int idProducto;
	private String nombre;
	private String medida;
	private double pesoUnitario;
	private String observaciones;
	private Set <RenglonOrdenProvisionInterna>renglonOrdenProvisionInternas = new HashSet<RenglonOrdenProvisionInterna>(0);
	private Set <RenglonListaDeMateriales>renglonListaDeMaterialeses = new HashSet<RenglonListaDeMateriales>(0);
	private Set <RenglonIngresoProductos>renglonIngresoProductoses = new HashSet<RenglonIngresoProductos>(0);
	private Set <Inventario>inventarios = new HashSet<Inventario>(0);
	private Set <RenglonOrdenCompraCotizacion>renglonOrdenCompraCotizacions = new HashSet<RenglonOrdenCompraCotizacion>(0);
	private Set <RequerimientoMateriales>requerimientoMaterialeses = new HashSet<RequerimientoMateriales>(0);

	public Producto() {
	}

	public Producto(int idProducto, String nombre, String medida,
			double pesoUnitario) {
		this.idProducto = idProducto;
		this.nombre = nombre;
		this.medida = medida;
		this.pesoUnitario = pesoUnitario;
	}

	public Producto(int idProducto, String nombre, String medida,
			double pesoUnitario, String observaciones,
			Set<RenglonOrdenProvisionInterna> renglonOrdenProvisionInternas, Set <RenglonListaDeMateriales>renglonListaDeMaterialeses,
			Set<RenglonIngresoProductos> renglonIngresoProductoses, Set<Inventario> inventarios,
			Set<RenglonOrdenCompraCotizacion> renglonOrdenCompraCotizacions, Set<RequerimientoMateriales> requerimientoMaterialeses) {
		this.idProducto = idProducto;
		this.nombre = nombre;
		this.medida = medida;
		this.pesoUnitario = pesoUnitario;
		this.observaciones = observaciones;
		this.renglonOrdenProvisionInternas = renglonOrdenProvisionInternas;
		this.renglonListaDeMaterialeses = renglonListaDeMaterialeses;
		this.renglonIngresoProductoses = renglonIngresoProductoses;
		this.inventarios = inventarios;
		this.renglonOrdenCompraCotizacions = renglonOrdenCompraCotizacions;
		this.requerimientoMaterialeses = requerimientoMaterialeses;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getMedida() {
		return this.medida;
	}

	public void setMedida(String medida) {
		this.medida = medida;
	}

	public double getPesoUnitario() {
		return this.pesoUnitario;
	}

	public void setPesoUnitario(double pesoUnitario) {
		this.pesoUnitario = pesoUnitario;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set<RenglonOrdenProvisionInterna> getRenglonOrdenProvisionInternas() {
		return this.renglonOrdenProvisionInternas;
	}

	public void setRenglonOrdenProvisionInternas(
			Set <RenglonOrdenProvisionInterna>renglonOrdenProvisionInternas) {
		this.renglonOrdenProvisionInternas = renglonOrdenProvisionInternas;
	}

	public Set <RenglonListaDeMateriales>getRenglonListaDeMaterialeses() {
		return this.renglonListaDeMaterialeses;
	}

	public void setRenglonListaDeMaterialeses(Set<RenglonListaDeMateriales> renglonListaDeMaterialeses) {
		this.renglonListaDeMaterialeses = renglonListaDeMaterialeses;
	}

	public Set<RenglonIngresoProductos> getRenglonIngresoProductoses() {
		return this.renglonIngresoProductoses;
	}

	public void setRenglonIngresoProductoses(Set <RenglonIngresoProductos>renglonIngresoProductoses) {
		this.renglonIngresoProductoses = renglonIngresoProductoses;
	}

	public Set<Inventario> getInventarios() {
		return this.inventarios;
	}

	public void setInventarios(Set<Inventario> inventarios) {
		this.inventarios = inventarios;
	}

	public Set<RenglonOrdenCompraCotizacion> getRenglonOrdenCompraCotizacions() {
		return this.renglonOrdenCompraCotizacions;
	}

	public void setRenglonOrdenCompraCotizacions(
			Set <RenglonOrdenCompraCotizacion>renglonOrdenCompraCotizacions) {
		this.renglonOrdenCompraCotizacions = renglonOrdenCompraCotizacions;
	}

	public Set<RequerimientoMateriales> getRequerimientoMaterialeses() {
		return this.requerimientoMaterialeses;
	}

	public void setRequerimientoMaterialeses(Set<RequerimientoMateriales> requerimientoMaterialeses) {
		this.requerimientoMaterialeses = requerimientoMaterialeses;
	}

}
