package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 213162808375401842L;
	private int idProvincia;
	private Pais pais;
	private String nombre;
	private Set<Localidad> localidads = new HashSet<Localidad>(0);

	public Provincia() {
	}

	public Provincia(int idProvincia, Pais pais, String nombre) {
		this.idProvincia = idProvincia;
		this.pais = pais;
		this.nombre = nombre;
	}

	public Provincia(int idProvincia, Pais pais, String nombre, Set <Localidad>localidads) {
		this.idProvincia = idProvincia;
		this.pais = pais;
		this.nombre = nombre;
		this.localidads = localidads;
	}

	public int getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Localidad> getLocalidads() {
		return this.localidads;
	}

	public void setLocalidads(Set<Localidad> localidads) {
		this.localidads = localidads;
	}

}
