package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * ProveedorDeInsumoId generated by hbm2java
 */
public class ProveedorDeInsumoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7176236707369126707L;
	private int idProveedor;
	private int idInsumo;

	public ProveedorDeInsumoId() {
	}

	public ProveedorDeInsumoId(int idProveedor, int idInsumo) {
		this.idProveedor = idProveedor;
		this.idInsumo = idInsumo;
	}

	public int getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(int idProveedor) {
		this.idProveedor = idProveedor;
	}

	public int getIdInsumo() {
		return this.idInsumo;
	}

	public void setIdInsumo(int idInsumo) {
		this.idInsumo = idInsumo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProveedorDeInsumoId))
			return false;
		ProveedorDeInsumoId castOther = (ProveedorDeInsumoId) other;

		return (this.getIdProveedor() == castOther.getIdProveedor())
				&& (this.getIdInsumo() == castOther.getIdInsumo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProveedor();
		result = 37 * result + this.getIdInsumo();
		return result;
	}

}
