package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * ProveedorDeProductoId generated by hbm2java
 */
public class ProveedorDeProductoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4394342979283997150L;
	private int idProveedor;
	private int idProducto;

	public ProveedorDeProductoId() {
	}

	public ProveedorDeProductoId(int idProveedor, int idProducto) {
		this.idProveedor = idProveedor;
		this.idProducto = idProducto;
	}

	public int getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(int idProveedor) {
		this.idProveedor = idProveedor;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProveedorDeProductoId))
			return false;
		ProveedorDeProductoId castOther = (ProveedorDeProductoId) other;

		return (this.getIdProveedor() == castOther.getIdProveedor())
				&& (this.getIdProducto() == castOther.getIdProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProveedor();
		result = 37 * result + this.getIdProducto();
		return result;
	}

}
