package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8018346859486668332L;
	private int codigoProveedor;
	private Direccion direccion;
	private String nombre;
	private String cuit;
	private String responsable;
	private String rubro;
	private String tipoProveedor;
	private String telefono;
	private String mail;
	private String fax;
	private String paginaWeb;
	private String observaciones;
	private Set <ProveedorDeInsumo>proveedorDeInsumos = new HashSet<ProveedorDeInsumo>(0);
	private Set <OrdenTrabajoSectorTercero>ordenTrabajoSectorTerceros = new HashSet<OrdenTrabajoSectorTercero>(0);
	private Set <Maquina>maquinas = new HashSet<Maquina>(0);
	private Set <OrdenCompraInsumo>ordenCompraInsumos = new HashSet<OrdenCompraInsumo>(0);
	private Set <ProveedorDeProducto>proveedorDeProductos = new HashSet<ProveedorDeProducto>(0);
	private Set <OrdenCompraCotizacion>ordenCompraCotizacions = new HashSet<OrdenCompraCotizacion>(0);
	private Set <Contacto>contactos = new HashSet<Contacto>(0);

	public Proveedor() {
	}

	public Proveedor(int codigoProveedor, Direccion direccion, String nombre,
			String cuit, String responsable, String tipoProveedor) {
		this.codigoProveedor = codigoProveedor;
		this.direccion = direccion;
		this.nombre = nombre;
		this.cuit = cuit;
		this.responsable = responsable;
		this.tipoProveedor = tipoProveedor;
	}

	public Proveedor(int codigoProveedor, Direccion direccion, String nombre,
			String cuit, String responsable, String rubro,
			String tipoProveedor, String telefono, String mail, String fax,
			String paginaWeb, String observaciones, Set<ProveedorDeInsumo> proveedorDeInsumos,
			Set <OrdenTrabajoSectorTercero>ordenTrabajoSectorTerceros, Set <Maquina>maquinas,
			Set <OrdenCompraInsumo>ordenCompraInsumos, Set <ProveedorDeProducto>proveedorDeProductos,
			Set <OrdenCompraCotizacion>ordenCompraCotizacions, Set <Contacto>contactos) {
		this.codigoProveedor = codigoProveedor;
		this.direccion = direccion;
		this.nombre = nombre;
		this.cuit = cuit;
		this.responsable = responsable;
		this.rubro = rubro;
		this.tipoProveedor = tipoProveedor;
		this.telefono = telefono;
		this.mail = mail;
		this.fax = fax;
		this.paginaWeb = paginaWeb;
		this.observaciones = observaciones;
		this.proveedorDeInsumos = proveedorDeInsumos;
		this.ordenTrabajoSectorTerceros = ordenTrabajoSectorTerceros;
		this.maquinas = maquinas;
		this.ordenCompraInsumos = ordenCompraInsumos;
		this.proveedorDeProductos = proveedorDeProductos;
		this.ordenCompraCotizacions = ordenCompraCotizacions;
		this.contactos = contactos;
	}

	public int getCodigoProveedor() {
		return this.codigoProveedor;
	}

	public void setCodigoProveedor(int codigoProveedor) {
		this.codigoProveedor = codigoProveedor;
	}

	public Direccion getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	public String getRubro() {
		return this.rubro;
	}

	public void setRubro(String rubro) {
		this.rubro = rubro;
	}

	public String getTipoProveedor() {
		return this.tipoProveedor;
	}

	public void setTipoProveedor(String tipoProveedor) {
		this.tipoProveedor = tipoProveedor;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getPaginaWeb() {
		return this.paginaWeb;
	}

	public void setPaginaWeb(String paginaWeb) {
		this.paginaWeb = paginaWeb;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set<ProveedorDeInsumo> getProveedorDeInsumos() {
		return this.proveedorDeInsumos;
	}

	public void setProveedorDeInsumos(Set<ProveedorDeInsumo> proveedorDeInsumos) {
		this.proveedorDeInsumos = proveedorDeInsumos;
	}

	public Set<OrdenTrabajoSectorTercero> getOrdenTrabajoSectorTerceros() {
		return this.ordenTrabajoSectorTerceros;
	}

	public void setOrdenTrabajoSectorTerceros(Set<OrdenTrabajoSectorTercero> ordenTrabajoSectorTerceros) {
		this.ordenTrabajoSectorTerceros = ordenTrabajoSectorTerceros;
	}

	public Set <Maquina>getMaquinas() {
		return this.maquinas;
	}

	public void setMaquinas(Set<Maquina> maquinas) {
		this.maquinas = maquinas;
	}

	public Set <OrdenCompraInsumo>getOrdenCompraInsumos() {
		return this.ordenCompraInsumos;
	}

	public void setOrdenCompraInsumos(Set <OrdenCompraInsumo>ordenCompraInsumos) {
		this.ordenCompraInsumos = ordenCompraInsumos;
	}

	public Set<ProveedorDeProducto> getProveedorDeProductos() {
		return this.proveedorDeProductos;
	}

	public void setProveedorDeProductos(Set<ProveedorDeProducto> proveedorDeProductos) {
		this.proveedorDeProductos = proveedorDeProductos;
	}

	public Set <OrdenCompraCotizacion>getOrdenCompraCotizacions() {
		return this.ordenCompraCotizacions;
	}

	public void setOrdenCompraCotizacions(Set<OrdenCompraCotizacion> ordenCompraCotizacions) {
		this.ordenCompraCotizacions = ordenCompraCotizacions;
	}

	public Set<Contacto> getContactos() {
		return this.contactos;
	}

	public void setContactos(Set<Contacto> contactos) {
		this.contactos = contactos;
	}

}
