package edu.server.repositorio;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RemitoMateriales generated by hbm2java
 */
public class RemitoMateriales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2038512852469136011L;
	private long idRemitoInternoMateriales;
	private Empleado empleado;
	private EstadoOrden estadoOrden;
	private OrdenProvisionInterna ordenProvisionInterna;
	private Date fechaGeneracion;
	private Date fechaCierre;
	private boolean recibido;
	private boolean remitoExterno;
	private String nroRemitoExterno;
	private String observaciones;
	private Set <RenglonRemitoMateriales>renglonRemitoMaterialeses = new HashSet<RenglonRemitoMateriales>(0);

	public RemitoMateriales() {
	}

	public RemitoMateriales(long idRemitoInternoMateriales, Empleado empleado,
			EstadoOrden estadoOrden,
			OrdenProvisionInterna ordenProvisionInterna, Date fechaGeneracion,
			boolean recibido, boolean remitoExterno) {
		this.idRemitoInternoMateriales = idRemitoInternoMateriales;
		this.empleado = empleado;
		this.estadoOrden = estadoOrden;
		this.ordenProvisionInterna = ordenProvisionInterna;
		this.fechaGeneracion = fechaGeneracion;
		this.recibido = recibido;
		this.remitoExterno = remitoExterno;
	}

	public RemitoMateriales(long idRemitoInternoMateriales, Empleado empleado,
			EstadoOrden estadoOrden,
			OrdenProvisionInterna ordenProvisionInterna, Date fechaGeneracion,
			Date fechaCierre, boolean recibido, boolean remitoExterno,
			String nroRemitoExterno, String observaciones,
			Set<RenglonRemitoMateriales> renglonRemitoMaterialeses) {
		this.idRemitoInternoMateriales = idRemitoInternoMateriales;
		this.empleado = empleado;
		this.estadoOrden = estadoOrden;
		this.ordenProvisionInterna = ordenProvisionInterna;
		this.fechaGeneracion = fechaGeneracion;
		this.fechaCierre = fechaCierre;
		this.recibido = recibido;
		this.remitoExterno = remitoExterno;
		this.nroRemitoExterno = nroRemitoExterno;
		this.observaciones = observaciones;
		this.renglonRemitoMaterialeses = renglonRemitoMaterialeses;
	}

	public long getIdRemitoInternoMateriales() {
		return this.idRemitoInternoMateriales;
	}

	public void setIdRemitoInternoMateriales(long idRemitoInternoMateriales) {
		this.idRemitoInternoMateriales = idRemitoInternoMateriales;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public EstadoOrden getEstadoOrden() {
		return this.estadoOrden;
	}

	public void setEstadoOrden(EstadoOrden estadoOrden) {
		this.estadoOrden = estadoOrden;
	}

	public OrdenProvisionInterna getOrdenProvisionInterna() {
		return this.ordenProvisionInterna;
	}

	public void setOrdenProvisionInterna(
			OrdenProvisionInterna ordenProvisionInterna) {
		this.ordenProvisionInterna = ordenProvisionInterna;
	}

	public Date getFechaGeneracion() {
		return this.fechaGeneracion;
	}

	public void setFechaGeneracion(Date fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public boolean isRecibido() {
		return this.recibido;
	}

	public void setRecibido(boolean recibido) {
		this.recibido = recibido;
	}

	public boolean isRemitoExterno() {
		return this.remitoExterno;
	}

	public void setRemitoExterno(boolean remitoExterno) {
		this.remitoExterno = remitoExterno;
	}

	public String getNroRemitoExterno() {
		return this.nroRemitoExterno;
	}

	public void setNroRemitoExterno(String nroRemitoExterno) {
		this.nroRemitoExterno = nroRemitoExterno;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set<RenglonRemitoMateriales> getRenglonRemitoMaterialeses() {
		return this.renglonRemitoMaterialeses;
	}

	public void setRenglonRemitoMaterialeses(Set <RenglonRemitoMateriales>renglonRemitoMaterialeses) {
		this.renglonRemitoMaterialeses = renglonRemitoMaterialeses;
	}

}
