package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonOrdenProvisionInsumo generated by hbm2java
 */
public class RenglonOrdenProvisionInsumo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8089219423066652489L;
	private RenglonOrdenProvisionInsumoId id;
	private OrdenProvisionInsumo ordenProvisionInsumo;
	private Insumo insumo;
	private Double cantidadRequerida;

	public RenglonOrdenProvisionInsumo() {
	}

	public RenglonOrdenProvisionInsumo(RenglonOrdenProvisionInsumoId id,
			OrdenProvisionInsumo ordenProvisionInsumo, Insumo insumo,
			Double cantidadRequerida) {
		this.id = id;
		this.ordenProvisionInsumo = ordenProvisionInsumo;
		this.insumo = insumo;
		this.cantidadRequerida = cantidadRequerida;
	}

	public RenglonOrdenProvisionInsumoId getId() {
		return this.id;
	}

	public void setId(RenglonOrdenProvisionInsumoId id) {
		this.id = id;
	}

	public OrdenProvisionInsumo getOrdenProvisionInsumo() {
		return this.ordenProvisionInsumo;
	}

	public void setOrdenProvisionInsumo(
			OrdenProvisionInsumo ordenProvisionInsumo) {
		this.ordenProvisionInsumo = ordenProvisionInsumo;
	}

	public Insumo getInsumo() {
		return this.insumo;
	}

	public void setInsumo(Insumo insumo) {
		this.insumo = insumo;
	}

	public Double getCantidadRequerida() {
		return this.cantidadRequerida;
	}

	public void setCantidadRequerida(Double cantidadRequerida) {
		this.cantidadRequerida = cantidadRequerida;
	}

}
