package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonOrdenCompraInsumoId generated by hbm2java
 */
public class RenglonOrdenCompraInsumoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3224129820913053668L;
	private int idRenglonOrdenCompraInsumo;
	private long nroOrdenCompraInsumo;

	public RenglonOrdenCompraInsumoId() {
	}

	public RenglonOrdenCompraInsumoId(int idRenglonOrdenCompraInsumo,
			long nroOrdenCompraInsumo) {
		this.idRenglonOrdenCompraInsumo = idRenglonOrdenCompraInsumo;
		this.nroOrdenCompraInsumo = nroOrdenCompraInsumo;
	}

	public int getIdRenglonOrdenCompraInsumo() {
		return this.idRenglonOrdenCompraInsumo;
	}

	public void setIdRenglonOrdenCompraInsumo(int idRenglonOrdenCompraInsumo) {
		this.idRenglonOrdenCompraInsumo = idRenglonOrdenCompraInsumo;
	}

	public long getNroOrdenCompraInsumo() {
		return this.nroOrdenCompraInsumo;
	}

	public void setNroOrdenCompraInsumo(long nroOrdenCompraInsumo) {
		this.nroOrdenCompraInsumo = nroOrdenCompraInsumo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonOrdenCompraInsumoId))
			return false;
		RenglonOrdenCompraInsumoId castOther = (RenglonOrdenCompraInsumoId) other;

		return (this.getIdRenglonOrdenCompraInsumo() == castOther
				.getIdRenglonOrdenCompraInsumo())
				&& (this.getNroOrdenCompraInsumo() == castOther
						.getNroOrdenCompraInsumo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonOrdenCompraInsumo();
		result = 37 * result + (int) this.getNroOrdenCompraInsumo();
		return result;
	}

}
