package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonRemitoMaterialesId generated by hbm2java
 */
public class RenglonRemitoMaterialesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4188305802650627543L;
	private int idRenglonRemitoInternoMateriales;
	private long idRemitoInternoMateriales;

	public RenglonRemitoMaterialesId() {
	}

	public RenglonRemitoMaterialesId(int idRenglonRemitoInternoMateriales,
			long idRemitoInternoMateriales) {
		this.idRenglonRemitoInternoMateriales = idRenglonRemitoInternoMateriales;
		this.idRemitoInternoMateriales = idRemitoInternoMateriales;
	}

	public int getIdRenglonRemitoInternoMateriales() {
		return this.idRenglonRemitoInternoMateriales;
	}

	public void setIdRenglonRemitoInternoMateriales(
			int idRenglonRemitoInternoMateriales) {
		this.idRenglonRemitoInternoMateriales = idRenglonRemitoInternoMateriales;
	}

	public long getIdRemitoInternoMateriales() {
		return this.idRemitoInternoMateriales;
	}

	public void setIdRemitoInternoMateriales(long idRemitoInternoMateriales) {
		this.idRemitoInternoMateriales = idRemitoInternoMateriales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonRemitoMaterialesId))
			return false;
		RenglonRemitoMaterialesId castOther = (RenglonRemitoMaterialesId) other;

		return (this.getIdRenglonRemitoInternoMateriales() == castOther
				.getIdRenglonRemitoInternoMateriales())
				&& (this.getIdRemitoInternoMateriales() == castOther
						.getIdRemitoInternoMateriales());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonRemitoInternoMateriales();
		result = 37 * result + (int) this.getIdRemitoInternoMateriales();
		return result;
	}

}
