package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonRemitoMateriales generated by hbm2java
 */
public class RenglonRemitoMateriales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7898213336367365799L;
	private RenglonRemitoMaterialesId id;
	private RemitoMateriales remitoMateriales;
	private RenglonOrdenProvisionInterna renglonOrdenProvisionInterna;
	private int idProducto;
	private double cantidadEntregada;

	public RenglonRemitoMateriales() {
	}

	public RenglonRemitoMateriales(RenglonRemitoMaterialesId id,
			RemitoMateriales remitoMateriales,
			RenglonOrdenProvisionInterna renglonOrdenProvisionInterna,
			int idProducto, double cantidadEntregada) {
		this.id = id;
		this.remitoMateriales = remitoMateriales;
		this.renglonOrdenProvisionInterna = renglonOrdenProvisionInterna;
		this.idProducto = idProducto;
		this.cantidadEntregada = cantidadEntregada;
	}

	public RenglonRemitoMaterialesId getId() {
		return this.id;
	}

	public void setId(RenglonRemitoMaterialesId id) {
		this.id = id;
	}

	public RemitoMateriales getRemitoMateriales() {
		return this.remitoMateriales;
	}

	public void setRemitoMateriales(RemitoMateriales remitoMateriales) {
		this.remitoMateriales = remitoMateriales;
	}

	public RenglonOrdenProvisionInterna getRenglonOrdenProvisionInterna() {
		return this.renglonOrdenProvisionInterna;
	}

	public void setRenglonOrdenProvisionInterna(
			RenglonOrdenProvisionInterna renglonOrdenProvisionInterna) {
		this.renglonOrdenProvisionInterna = renglonOrdenProvisionInterna;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public double getCantidadEntregada() {
		return this.cantidadEntregada;
	}

	public void setCantidadEntregada(double cantidadEntregada) {
		this.cantidadEntregada = cantidadEntregada;
	}

}
