package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonOrdenProvisionInsumoId generated by hbm2java
 */
public class RenglonOrdenProvisionInsumoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8936153941712127561L;
	private int idRenglon;
	private long idOrdenProvisionInsumo;

	public RenglonOrdenProvisionInsumoId() {
	}

	public RenglonOrdenProvisionInsumoId(int idRenglon,
			long idOrdenProvisionInsumo) {
		this.idRenglon = idRenglon;
		this.idOrdenProvisionInsumo = idOrdenProvisionInsumo;
	}

	public int getIdRenglon() {
		return this.idRenglon;
	}

	public void setIdRenglon(int idRenglon) {
		this.idRenglon = idRenglon;
	}

	public long getIdOrdenProvisionInsumo() {
		return this.idOrdenProvisionInsumo;
	}

	public void setIdOrdenProvisionInsumo(long idOrdenProvisionInsumo) {
		this.idOrdenProvisionInsumo = idOrdenProvisionInsumo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonOrdenProvisionInsumoId))
			return false;
		RenglonOrdenProvisionInsumoId castOther = (RenglonOrdenProvisionInsumoId) other;

		return (this.getIdRenglon() == castOther.getIdRenglon())
				&& (this.getIdOrdenProvisionInsumo() == castOther
						.getIdOrdenProvisionInsumo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglon();
		result = 37 * result + (int) this.getIdOrdenProvisionInsumo();
		return result;
	}

}
