package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonOrdenFabricacionGeneralId generated by hbm2java
 */
public class RenglonOrdenFabricacionGeneralId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6695782105349467444L;
	private int idRenglonOrdenFabricacion;
	private long idOrdenFabricacion;

	public RenglonOrdenFabricacionGeneralId() {
	}

	public RenglonOrdenFabricacionGeneralId(int idRenglonOrdenFabricacion,
			long idOrdenFabricacion) {
		this.idRenglonOrdenFabricacion = idRenglonOrdenFabricacion;
		this.idOrdenFabricacion = idOrdenFabricacion;
	}

	public int getIdRenglonOrdenFabricacion() {
		return this.idRenglonOrdenFabricacion;
	}

	public void setIdRenglonOrdenFabricacion(int idRenglonOrdenFabricacion) {
		this.idRenglonOrdenFabricacion = idRenglonOrdenFabricacion;
	}

	public long getIdOrdenFabricacion() {
		return this.idOrdenFabricacion;
	}

	public void setIdOrdenFabricacion(long idOrdenFabricacion) {
		this.idOrdenFabricacion = idOrdenFabricacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonOrdenFabricacionGeneralId))
			return false;
		RenglonOrdenFabricacionGeneralId castOther = (RenglonOrdenFabricacionGeneralId) other;

		return (this.getIdRenglonOrdenFabricacion() == castOther
				.getIdRenglonOrdenFabricacion())
				&& (this.getIdOrdenFabricacion() == castOther
						.getIdOrdenFabricacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonOrdenFabricacion();
		result = 37 * result + (int) this.getIdOrdenFabricacion();
		return result;
	}

}
