package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonIngresoInsumosId generated by hbm2java
 */
public class RenglonIngresoInsumosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7858408734927687679L;
	private int idRenglonIngresoInsumos;
	private long idOrdenCompraInsumos;
	private long nroRemitoExterno;

	public RenglonIngresoInsumosId() {
	}

	public RenglonIngresoInsumosId(int idRenglonIngresoInsumos,
			long idOrdenCompraInsumos, long nroRemitoExterno) {
		this.idRenglonIngresoInsumos = idRenglonIngresoInsumos;
		this.idOrdenCompraInsumos = idOrdenCompraInsumos;
		this.nroRemitoExterno = nroRemitoExterno;
	}

	public int getIdRenglonIngresoInsumos() {
		return this.idRenglonIngresoInsumos;
	}

	public void setIdRenglonIngresoInsumos(int idRenglonIngresoInsumos) {
		this.idRenglonIngresoInsumos = idRenglonIngresoInsumos;
	}

	public long getIdOrdenCompraInsumos() {
		return this.idOrdenCompraInsumos;
	}

	public void setIdOrdenCompraInsumos(long idOrdenCompraInsumos) {
		this.idOrdenCompraInsumos = idOrdenCompraInsumos;
	}

	public long getNroRemitoExterno() {
		return this.nroRemitoExterno;
	}

	public void setNroRemitoExterno(long nroRemitoExterno) {
		this.nroRemitoExterno = nroRemitoExterno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonIngresoInsumosId))
			return false;
		RenglonIngresoInsumosId castOther = (RenglonIngresoInsumosId) other;

		return (this.getIdRenglonIngresoInsumos() == castOther
				.getIdRenglonIngresoInsumos())
				&& (this.getIdOrdenCompraInsumos() == castOther
						.getIdOrdenCompraInsumos())
				&& (this.getNroRemitoExterno() == castOther
						.getNroRemitoExterno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonIngresoInsumos();
		result = 37 * result + (int) this.getIdOrdenCompraInsumos();
		result = 37 * result + (int) this.getNroRemitoExterno();
		return result;
	}

}
