package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonOrdenTrabajoId generated by hbm2java
 */
public class RenglonOrdenTrabajoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2054915876652298312L;
	private int idRenglonOrdenTrabajo;
	private long idOrdenTrabajo;

	public RenglonOrdenTrabajoId() {
	}

	public RenglonOrdenTrabajoId(int idRenglonOrdenTrabajo, long idOrdenTrabajo) {
		this.idRenglonOrdenTrabajo = idRenglonOrdenTrabajo;
		this.idOrdenTrabajo = idOrdenTrabajo;
	}

	public int getIdRenglonOrdenTrabajo() {
		return this.idRenglonOrdenTrabajo;
	}

	public void setIdRenglonOrdenTrabajo(int idRenglonOrdenTrabajo) {
		this.idRenglonOrdenTrabajo = idRenglonOrdenTrabajo;
	}

	public long getIdOrdenTrabajo() {
		return this.idOrdenTrabajo;
	}

	public void setIdOrdenTrabajo(long idOrdenTrabajo) {
		this.idOrdenTrabajo = idOrdenTrabajo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonOrdenTrabajoId))
			return false;
		RenglonOrdenTrabajoId castOther = (RenglonOrdenTrabajoId) other;

		return (this.getIdRenglonOrdenTrabajo() == castOther
				.getIdRenglonOrdenTrabajo())
				&& (this.getIdOrdenTrabajo() == castOther.getIdOrdenTrabajo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonOrdenTrabajo();
		result = 37 * result + (int) this.getIdOrdenTrabajo();
		return result;
	}

}
