package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonRemitoInternoInsumoId generated by hbm2java
 */
public class RenglonRemitoInternoInsumoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7743208175333445391L;
	private int idRenglonRemitoInsumo;
	private long idRemitoInsumo;

	public RenglonRemitoInternoInsumoId() {
	}

	public RenglonRemitoInternoInsumoId(int idRenglonRemitoInsumo,
			long idRemitoInsumo) {
		this.idRenglonRemitoInsumo = idRenglonRemitoInsumo;
		this.idRemitoInsumo = idRemitoInsumo;
	}

	public int getIdRenglonRemitoInsumo() {
		return this.idRenglonRemitoInsumo;
	}

	public void setIdRenglonRemitoInsumo(int idRenglonRemitoInsumo) {
		this.idRenglonRemitoInsumo = idRenglonRemitoInsumo;
	}

	public long getIdRemitoInsumo() {
		return this.idRemitoInsumo;
	}

	public void setIdRemitoInsumo(long idRemitoInsumo) {
		this.idRemitoInsumo = idRemitoInsumo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonRemitoInternoInsumoId))
			return false;
		RenglonRemitoInternoInsumoId castOther = (RenglonRemitoInternoInsumoId) other;

		return (this.getIdRenglonRemitoInsumo() == castOther
				.getIdRenglonRemitoInsumo())
				&& (this.getIdRemitoInsumo() == castOther.getIdRemitoInsumo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonRemitoInsumo();
		result = 37 * result + (int) this.getIdRemitoInsumo();
		return result;
	}

}
