package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonOrdenCompraInsumo generated by hbm2java
 */
public class RenglonOrdenCompraInsumo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3575369335587955279L;
	private RenglonOrdenCompraInsumoId id;
	private Insumo insumo;
	private OrdenCompraInsumo ordenCompraInsumo;
	private Double cantidad;
	private Double subtotal;

	public RenglonOrdenCompraInsumo() {
	}

	public RenglonOrdenCompraInsumo(RenglonOrdenCompraInsumoId id,
			Insumo insumo, OrdenCompraInsumo ordenCompraInsumo, Double cantidad) {
		this.id = id;
		this.insumo = insumo;
		this.ordenCompraInsumo = ordenCompraInsumo;
		this.cantidad = cantidad;
	}

	public RenglonOrdenCompraInsumo(RenglonOrdenCompraInsumoId id,
			Insumo insumo, OrdenCompraInsumo ordenCompraInsumo,
			Double cantidad, Double subtotal) {
		this.id = id;
		this.insumo = insumo;
		this.ordenCompraInsumo = ordenCompraInsumo;
		this.cantidad = cantidad;
		this.subtotal = subtotal;
	}

	public RenglonOrdenCompraInsumoId getId() {
		return this.id;
	}

	public void setId(RenglonOrdenCompraInsumoId id) {
		this.id = id;
	}

	public Insumo getInsumo() {
		return this.insumo;
	}

	public void setInsumo(Insumo insumo) {
		this.insumo = insumo;
	}

	public OrdenCompraInsumo getOrdenCompraInsumo() {
		return this.ordenCompraInsumo;
	}

	public void setOrdenCompraInsumo(OrdenCompraInsumo ordenCompraInsumo) {
		this.ordenCompraInsumo = ordenCompraInsumo;
	}

	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(double cantidad) {
		this.cantidad = cantidad;
	}

	public Double getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Double subtotal) {
		this.subtotal = subtotal;
	}
	
	public void setSubtotal() {
		this.subtotal = null;
	}

	
	
}
