package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonIngresoInsumos generated by hbm2java
 */
public class RenglonIngresoInsumos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6746170338531093258L;
	private RenglonIngresoInsumosId id;
	private IngresoInsumos ingresoInsumos;
	private Insumo insumo;
	private double cantidadIngresada;

	public RenglonIngresoInsumos() {
	}

	public RenglonIngresoInsumos(RenglonIngresoInsumosId id,
			IngresoInsumos ingresoInsumos, Insumo insumo,
			double cantidadIngresada) {
		this.id = id;
		this.ingresoInsumos = ingresoInsumos;
		this.insumo = insumo;
		this.cantidadIngresada = cantidadIngresada;
	}

	public RenglonIngresoInsumosId getId() {
		return this.id;
	}

	public void setId(RenglonIngresoInsumosId id) {
		this.id = id;
	}

	public IngresoInsumos getIngresoInsumos() {
		return this.ingresoInsumos;
	}

	public void setIngresoInsumos(IngresoInsumos ingresoInsumos) {
		this.ingresoInsumos = ingresoInsumos;
	}

	public Insumo getInsumo() {
		return this.insumo;
	}

	public void setInsumo(Insumo insumo) {
		this.insumo = insumo;
	}

	public double getCantidadIngresada() {
		return this.cantidadIngresada;
	}

	public void setCantidadIngresada(double cantidadIngresada) {
		this.cantidadIngresada = cantidadIngresada;
	}

}
