package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonOrdenPedidoId generated by hbm2java
 */
public class RenglonOrdenPedidoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8081774348243148135L;
	private int idRenglonOrdenPedido;
	private long idOrdenPedido;

	public RenglonOrdenPedidoId() {
	}

	public RenglonOrdenPedidoId(int idRenglonOrdenPedido, long idOrdenPedido) {
		this.idRenglonOrdenPedido = idRenglonOrdenPedido;
		this.idOrdenPedido = idOrdenPedido;
	}

	public int getIdRenglonOrdenPedido() {
		return this.idRenglonOrdenPedido;
	}

	public void setIdRenglonOrdenPedido(int idRenglonOrdenPedido) {
		this.idRenglonOrdenPedido = idRenglonOrdenPedido;
	}

	public long getIdOrdenPedido() {
		return this.idOrdenPedido;
	}

	public void setIdOrdenPedido(long idOrdenPedido) {
		this.idOrdenPedido = idOrdenPedido;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonOrdenPedidoId))
			return false;
		RenglonOrdenPedidoId castOther = (RenglonOrdenPedidoId) other;

		return (this.getIdRenglonOrdenPedido() == castOther
				.getIdRenglonOrdenPedido())
				&& (this.getIdOrdenPedido() == castOther.getIdOrdenPedido());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonOrdenPedido();
		result = 37 * result + (int) this.getIdOrdenPedido();
		return result;
	}

}
