package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonIngresoProductosId generated by hbm2java
 */
public class RenglonIngresoProductosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1732874222458619615L;
	private int idRenglonIngresoProductos;
	private long idIngreso;

	public RenglonIngresoProductosId() {
	}

	public RenglonIngresoProductosId(int idRenglonIngresoProductos,
			long idIngreso) {
		this.idRenglonIngresoProductos = idRenglonIngresoProductos;
		this.idIngreso = idIngreso;
	}

	public int getIdRenglonIngresoProductos() {
		return this.idRenglonIngresoProductos;
	}

	public void setIdRenglonIngresoProductos(int idRenglonIngresoProductos) {
		this.idRenglonIngresoProductos = idRenglonIngresoProductos;
	}

	public long getIdIngreso() {
		return this.idIngreso;
	}

	public void setIdIngreso(long idIngreso) {
		this.idIngreso = idIngreso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonIngresoProductosId))
			return false;
		RenglonIngresoProductosId castOther = (RenglonIngresoProductosId) other;

		return (this.getIdRenglonIngresoProductos() == castOther
				.getIdRenglonIngresoProductos())
				&& (this.getIdIngreso() == castOther.getIdIngreso());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonIngresoProductos();
		result = 37 * result + (int) this.getIdIngreso();
		return result;
	}

}
