package edu.server.repositorio;

import java.util.Date;

/**
 * RenglonOrdenPedido generated by hbm2java
 */
public class RenglonOrdenPedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -199315788168794675L;
	private RenglonOrdenPedidoId id;
	private Componente componente;
	private OrdenPedido ordenPedido;
	private Equipo equipo;
	private int cantidad;
	private Date fechaPrevistaFinalizacion;
	private String observaciones;

	public RenglonOrdenPedido() {
	}

	public RenglonOrdenPedido(RenglonOrdenPedidoId id, OrdenPedido ordenPedido,
			int cantidad, Date fechaPrevistaFinalizacion) {
		this.id = id;
		this.ordenPedido = ordenPedido;
		this.cantidad = cantidad;
		this.fechaPrevistaFinalizacion = fechaPrevistaFinalizacion;
	}

	public RenglonOrdenPedido(RenglonOrdenPedidoId id, Componente componente,
			OrdenPedido ordenPedido, Equipo equipo, int cantidad,
			Date fechaPrevistaFinalizacion, String observaciones) {
		this.id = id;
		this.componente = componente;
		this.ordenPedido = ordenPedido;
		this.equipo = equipo;
		this.cantidad = cantidad;
		this.fechaPrevistaFinalizacion = fechaPrevistaFinalizacion;
		this.observaciones = observaciones;
	}

	public RenglonOrdenPedidoId getId() {
		return this.id;
	}

	public void setId(RenglonOrdenPedidoId id) {
		this.id = id;
	}

	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	public OrdenPedido getOrdenPedido() {
		return this.ordenPedido;
	}

	public void setOrdenPedido(OrdenPedido ordenPedido) {
		this.ordenPedido = ordenPedido;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFechaPrevistaFinalizacion() {
		return this.fechaPrevistaFinalizacion;
	}

	public void setFechaPrevistaFinalizacion(Date fechaPrevistaFinalizacion) {
		this.fechaPrevistaFinalizacion = fechaPrevistaFinalizacion;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
