package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonIngresoProductos generated by hbm2java
 */
public class RenglonIngresoProductos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6756763127046649068L;
	private RenglonIngresoProductosId id;
	private Producto producto;
	private double cantidad;

	public RenglonIngresoProductos() {
	}

	public RenglonIngresoProductos(RenglonIngresoProductosId id,
			Producto producto, double cantidad) {
		this.id = id;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	public RenglonIngresoProductosId getId() {
		return this.id;
	}

	public void setId(RenglonIngresoProductosId id) {
		this.id = id;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(double cantidad) {
		this.cantidad = cantidad;
	}

}
