package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonRemitoInternoInsumo generated by hbm2java
 */
public class RenglonRemitoInternoInsumo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5867627762111217852L;
	private RenglonRemitoInternoInsumoId id;
	private Insumo insumo;
	private RemitoInternoInsumo remitoInternoInsumo;
	private double cantidadEntregada;

	public RenglonRemitoInternoInsumo() {
	}

	public RenglonRemitoInternoInsumo(RenglonRemitoInternoInsumoId id,
			Insumo insumo, RemitoInternoInsumo remitoInternoInsumo,
			double cantidadEntregada) {
		this.id = id;
		this.insumo = insumo;
		this.remitoInternoInsumo = remitoInternoInsumo;
		this.cantidadEntregada = cantidadEntregada;
	}

	public RenglonRemitoInternoInsumoId getId() {
		return this.id;
	}

	public void setId(RenglonRemitoInternoInsumoId id) {
		this.id = id;
	}

	public Insumo getInsumo() {
		return this.insumo;
	}

	public void setInsumo(Insumo insumo) {
		this.insumo = insumo;
	}

	public RemitoInternoInsumo getRemitoInternoInsumo() {
		return this.remitoInternoInsumo;
	}

	public void setRemitoInternoInsumo(RemitoInternoInsumo remitoInternoInsumo) {
		this.remitoInternoInsumo = remitoInternoInsumo;
	}

	public double getCantidadEntregada() {
		return this.cantidadEntregada;
	}

	public void setCantidadEntregada(double cantidadEntregada) {
		this.cantidadEntregada = cantidadEntregada;
	}

}
