package edu.server.repositorio;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RenglonOrdenTrabajo generated by hbm2java
 */
public class RenglonOrdenTrabajo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8292711296903926429L;
	private RenglonOrdenTrabajoId id;
	private Componente componente;
	private OrdenTrabajoSectorTercero ordenTrabajoSectorTercero;
	private Equipo equipo;
	private Empleado empleado;
	private Date fechaFinalizacion;
	private double cantidad;
	private String observaciones;
	private Set<OrdenProvisionInterna> ordenProvisionInternas = new HashSet<OrdenProvisionInterna>(0);

	public RenglonOrdenTrabajo() {
	}

	public RenglonOrdenTrabajo(RenglonOrdenTrabajoId id,
			OrdenTrabajoSectorTercero ordenTrabajoSectorTercero,
			Date fechaFinalizacion, double cantidad) {
		this.id = id;
		this.ordenTrabajoSectorTercero = ordenTrabajoSectorTercero;
		this.fechaFinalizacion = fechaFinalizacion;
		this.cantidad = cantidad;
	}

	public RenglonOrdenTrabajo(RenglonOrdenTrabajoId id, Componente componente,
			OrdenTrabajoSectorTercero ordenTrabajoSectorTercero, Equipo equipo,
			Empleado empleado, Date fechaFinalizacion, double cantidad,
			String observaciones, Set <OrdenProvisionInterna>ordenProvisionInternas) {
		this.id = id;
		this.componente = componente;
		this.ordenTrabajoSectorTercero = ordenTrabajoSectorTercero;
		this.equipo = equipo;
		this.empleado = empleado;
		this.fechaFinalizacion = fechaFinalizacion;
		this.cantidad = cantidad;
		this.observaciones = observaciones;
		this.ordenProvisionInternas = ordenProvisionInternas;
	}

	public RenglonOrdenTrabajoId getId() {
		return this.id;
	}

	public void setId(RenglonOrdenTrabajoId id) {
		this.id = id;
	}

	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	public OrdenTrabajoSectorTercero getOrdenTrabajoSectorTercero() {
		return this.ordenTrabajoSectorTercero;
	}

	public void setOrdenTrabajoSectorTercero(
			OrdenTrabajoSectorTercero ordenTrabajoSectorTercero) {
		this.ordenTrabajoSectorTercero = ordenTrabajoSectorTercero;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Date getFechaFinalizacion() {
		return this.fechaFinalizacion;
	}

	public void setFechaFinalizacion(Date fechaFinalizacion) {
		this.fechaFinalizacion = fechaFinalizacion;
	}

	public double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(double cantidad) {
		this.cantidad = cantidad;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set <OrdenProvisionInterna>getOrdenProvisionInternas() {
		return this.ordenProvisionInternas;
	}

	public void setOrdenProvisionInternas(Set <OrdenProvisionInterna>ordenProvisionInternas) {
		this.ordenProvisionInternas = ordenProvisionInternas;
	}

}
