package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonOrdenCompraCotizacionId generated by hbm2java
 */
public class RenglonOrdenCompraCotizacionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5302398909632855633L;
	private int idRenglonOrdenCompra;
	private long idOrdenCompra;

	public RenglonOrdenCompraCotizacionId() {
	}

	public RenglonOrdenCompraCotizacionId(int idRenglonOrdenCompra,
			long idOrdenCompra) {
		this.idRenglonOrdenCompra = idRenglonOrdenCompra;
		this.idOrdenCompra = idOrdenCompra;
	}

	public int getIdRenglonOrdenCompra() {
		return this.idRenglonOrdenCompra;
	}

	public void setIdRenglonOrdenCompra(int idRenglonOrdenCompra) {
		this.idRenglonOrdenCompra = idRenglonOrdenCompra;
	}

	public long getIdOrdenCompra() {
		return this.idOrdenCompra;
	}

	public void setIdOrdenCompra(long idOrdenCompra) {
		this.idOrdenCompra = idOrdenCompra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonOrdenCompraCotizacionId))
			return false;
		RenglonOrdenCompraCotizacionId castOther = (RenglonOrdenCompraCotizacionId) other;

		return (this.getIdRenglonOrdenCompra() == castOther
				.getIdRenglonOrdenCompra())
				&& (this.getIdOrdenCompra() == castOther.getIdOrdenCompra());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonOrdenCompra();
		result = 37 * result + (int) this.getIdOrdenCompra();
		return result;
	}

}
