package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonOrdenProvisionInternaId generated by hbm2java
 */
public class RenglonOrdenProvisionInternaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5125968482962694974L;
	private int idRenglonOrdenProvision;
	private long idOrdenProvision;

	public RenglonOrdenProvisionInternaId() {
	}

	public RenglonOrdenProvisionInternaId(int idRenglonOrdenProvision,
			long idOrdenProvision) {
		this.idRenglonOrdenProvision = idRenglonOrdenProvision;
		this.idOrdenProvision = idOrdenProvision;
	}

	public int getIdRenglonOrdenProvision() {
		return this.idRenglonOrdenProvision;
	}

	public void setIdRenglonOrdenProvision(int idRenglonOrdenProvision) {
		this.idRenglonOrdenProvision = idRenglonOrdenProvision;
	}

	public long getIdOrdenProvision() {
		return this.idOrdenProvision;
	}

	public void setIdOrdenProvision(long idOrdenProvision) {
		this.idOrdenProvision = idOrdenProvision;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonOrdenProvisionInternaId))
			return false;
		RenglonOrdenProvisionInternaId castOther = (RenglonOrdenProvisionInternaId) other;

		return (this.getIdRenglonOrdenProvision() == castOther
				.getIdRenglonOrdenProvision())
				&& (this.getIdOrdenProvision() == castOther
						.getIdOrdenProvision());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRenglonOrdenProvision();
		result = 37 * result + (int) this.getIdOrdenProvision();
		return result;
	}

}
