package edu.server.repositorio;

import java.util.Date;

/**
 * RenglonOrdenFabricacionGeneral generated by hbm2java
 */
public class RenglonOrdenFabricacionGeneral implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1472705295757368907L;
	private RenglonOrdenFabricacionGeneralId id;
	private Componente componente;
	private OrdenFabricacionGeneral ordenFabricacionGeneral;
	private Equipo equipo;
	private int cantidad;
	private Date fechaFinalizacion;
	private String observaciones;

	public RenglonOrdenFabricacionGeneral() {
	}

	public RenglonOrdenFabricacionGeneral(RenglonOrdenFabricacionGeneralId id,
			OrdenFabricacionGeneral ordenFabricacionGeneral, int cantidad,
			Date fechaFinalizacion) {
		this.id = id;
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
		this.cantidad = cantidad;
		this.fechaFinalizacion = fechaFinalizacion;
	}

	public RenglonOrdenFabricacionGeneral(RenglonOrdenFabricacionGeneralId id,
			Componente componente,
			OrdenFabricacionGeneral ordenFabricacionGeneral, Equipo equipo,
			int cantidad, Date fechaFinalizacion, String observaciones) {
		this.id = id;
		this.componente = componente;
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
		this.equipo = equipo;
		this.cantidad = cantidad;
		this.fechaFinalizacion = fechaFinalizacion;
		this.observaciones = observaciones;
	}

	public RenglonOrdenFabricacionGeneralId getId() {
		return this.id;
	}

	public void setId(RenglonOrdenFabricacionGeneralId id) {
		this.id = id;
	}

	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	public OrdenFabricacionGeneral getOrdenFabricacionGeneral() {
		return this.ordenFabricacionGeneral;
	}

	public void setOrdenFabricacionGeneral(
			OrdenFabricacionGeneral ordenFabricacionGeneral) {
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFechaFinalizacion() {
		return this.fechaFinalizacion;
	}

	public void setFechaFinalizacion(Date fechaFinalizacion) {
		this.fechaFinalizacion = fechaFinalizacion;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
