package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonListaDeMateriales generated by hbm2java
 */
public class RenglonListaDeMateriales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7946226025793468973L;
	private RenglonListaDeMaterialesId id;
	private Componente componente;
	private ListaDeMateriales listaDeMateriales;
	private Producto producto;
	private int cantidad;
	private int td;
	private String medida1;
	private String medida2;

	public RenglonListaDeMateriales() {
	}

	public RenglonListaDeMateriales(RenglonListaDeMaterialesId id,
			ListaDeMateriales listaDeMateriales, int cantidad, int td) {
		this.id = id;
		this.listaDeMateriales = listaDeMateriales;
		this.cantidad = cantidad;
		this.td = td;
	}

	public RenglonListaDeMateriales(RenglonListaDeMaterialesId id,
			Componente componente, ListaDeMateriales listaDeMateriales,
			Producto producto, int cantidad, int td, String medida1,
			String medida2) {
		this.id = id;
		this.componente = componente;
		this.listaDeMateriales = listaDeMateriales;
		this.producto = producto;
		this.cantidad = cantidad;
		this.td = td;
		this.medida1 = medida1;
		this.medida2 = medida2;
	}

	public RenglonListaDeMaterialesId getId() {
		return this.id;
	}

	public void setId(RenglonListaDeMaterialesId id) {
		this.id = id;
	}

	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	public ListaDeMateriales getListaDeMateriales() {
		return this.listaDeMateriales;
	}

	public void setListaDeMateriales(ListaDeMateriales listaDeMateriales) {
		this.listaDeMateriales = listaDeMateriales;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public int getTd() {
		return this.td;
	}

	public void setTd(int td) {
		this.td = td;
	}

	public String getMedida1() {
		return this.medida1;
	}

	public void setMedida1(String medida1) {
		this.medida1 = medida1;
	}

	public String getMedida2() {
		return this.medida2;
	}

	public void setMedida2(String medida2) {
		this.medida2 = medida2;
	}

}
