package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * RenglonListaDeMaterialesId generated by hbm2java
 */
public class RenglonListaDeMaterialesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3567777892921681467L;
	private int idListaDeMateriales;
	private int idRenglon;

	public RenglonListaDeMaterialesId() {
	}

	public RenglonListaDeMaterialesId(int idListaDeMateriales, int idRenglon) {
		this.idListaDeMateriales = idListaDeMateriales;
		this.idRenglon = idRenglon;
	}

	public int getIdListaDeMateriales() {
		return this.idListaDeMateriales;
	}

	public void setIdListaDeMateriales(int idListaDeMateriales) {
		this.idListaDeMateriales = idListaDeMateriales;
	}

	public int getIdRenglon() {
		return this.idRenglon;
	}

	public void setIdRenglon(int idRenglon) {
		this.idRenglon = idRenglon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenglonListaDeMaterialesId))
			return false;
		RenglonListaDeMaterialesId castOther = (RenglonListaDeMaterialesId) other;

		return (this.getIdListaDeMateriales() == castOther
				.getIdListaDeMateriales())
				&& (this.getIdRenglon() == castOther.getIdRenglon());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdListaDeMateriales();
		result = 37 * result + this.getIdRenglon();
		return result;
	}

}
