package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * ReservaComponente generated by hbm2java
 */
public class ReservaComponente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8881391159183782007L;
	private int idReservaComponente;
	private OrdenFabricacionGeneral ordenFabricacionGeneral;
	private int idComponente;
	private int cantidadReservada;

	public ReservaComponente() {
	}

	public ReservaComponente(int idReservaComponente,
			OrdenFabricacionGeneral ordenFabricacionGeneral, int idComponente,
			int cantidadReservada) {
		this.idReservaComponente = idReservaComponente;
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
		this.idComponente = idComponente;
		this.cantidadReservada = cantidadReservada;
	}

	public int getIdReservaComponente() {
		return this.idReservaComponente;
	}

	public void setIdReservaComponente(int idReservaComponente) {
		this.idReservaComponente = idReservaComponente;
	}

	public OrdenFabricacionGeneral getOrdenFabricacionGeneral() {
		return this.ordenFabricacionGeneral;
	}

	public void setOrdenFabricacionGeneral(
			OrdenFabricacionGeneral ordenFabricacionGeneral) {
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
	}

	public int getIdComponente() {
		return this.idComponente;
	}

	public void setIdComponente(int idComponente) {
		this.idComponente = idComponente;
	}

	public int getCantidadReservada() {
		return this.cantidadReservada;
	}

	public void setCantidadReservada(int cantidadReservada) {
		this.cantidadReservada = cantidadReservada;
	}

}
