package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * Reserva generated by hbm2java
 */
public class Reserva implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4419204768723065630L;
	private int idReserva;
	private OrdenFabricacionGeneral ordenFabricacionGeneral;
	private Inventario inventario;
	private double cantidadReservada;
	private Double cantReservadaPendienteEntrega;

	public Reserva() {
	}

	public Reserva(int idReserva,
			OrdenFabricacionGeneral ordenFabricacionGeneral,
			Inventario inventario, double cantidadReservada) {
		this.idReserva = idReserva;
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
		this.inventario = inventario;
		this.cantidadReservada = cantidadReservada;
	}

	public Reserva(int idReserva,
			OrdenFabricacionGeneral ordenFabricacionGeneral,
			Inventario inventario, double cantidadReservada,
			Double cantReservadaPendienteEntrega) {
		this.idReserva = idReserva;
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
		this.inventario = inventario;
		this.cantidadReservada = cantidadReservada;
		this.cantReservadaPendienteEntrega = cantReservadaPendienteEntrega;
	}

	public int getIdReserva() {
		return this.idReserva;
	}

	public void setIdReserva(int idReserva) {
		this.idReserva = idReserva;
	}

	public OrdenFabricacionGeneral getOrdenFabricacionGeneral() {
		return this.ordenFabricacionGeneral;
	}

	public void setOrdenFabricacionGeneral(
			OrdenFabricacionGeneral ordenFabricacionGeneral) {
		this.ordenFabricacionGeneral = ordenFabricacionGeneral;
	}

	public Inventario getInventario() {
		return this.inventario;
	}

	public void setInventario(Inventario inventario) {
		this.inventario = inventario;
	}

	public double getCantidadReservada() {
		return this.cantidadReservada;
	}

	public void setCantidadReservada(double cantidadReservada) {
		this.cantidadReservada = cantidadReservada;
	}

	public Double getCantReservadaPendienteEntrega() {
		return this.cantReservadaPendienteEntrega;
	}

	public void setCantReservadaPendienteEntrega(
			Double cantReservadaPendienteEntrega) {
		this.cantReservadaPendienteEntrega = cantReservadaPendienteEntrega;
	}

}
