package edu.server.repositorio;

import java.util.HashSet;
import java.util.Set;

/**
 * SubclaseEquipo generated by hbm2java
 */
public class SubclaseEquipo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3883491889912332921L;
	private SubclaseEquipoId id;
	private ClaseEquipo claseEquipo;
	private String nombreSubclase;
	private String descripcion;
	private Set<Equipo> equipos = new HashSet<Equipo>(0);

	public SubclaseEquipo() {
	}

	public SubclaseEquipo(SubclaseEquipoId id, ClaseEquipo claseEquipo,
			String nombreSubclase) {
		this.id = id;
		this.claseEquipo = claseEquipo;
		this.nombreSubclase = nombreSubclase;
	}

	public SubclaseEquipo(SubclaseEquipoId id, ClaseEquipo claseEquipo,
			String nombreSubclase, String descripcion, Set<Equipo> equipos) {
		this.id = id;
		this.claseEquipo = claseEquipo;
		this.nombreSubclase = nombreSubclase;
		this.descripcion = descripcion;
		this.equipos = equipos;
	}

	public SubclaseEquipoId getId() {
		return this.id;
	}

	public void setId(SubclaseEquipoId id) {
		this.id = id;
	}

	public ClaseEquipo getClaseEquipo() {
		return this.claseEquipo;
	}

	public void setClaseEquipo(ClaseEquipo claseEquipo) {
		this.claseEquipo = claseEquipo;
	}

	public String getNombreSubclase() {
		return this.nombreSubclase;
	}

	public void setNombreSubclase(String nombreSubclase) {
		this.nombreSubclase = nombreSubclase;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Equipo> getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set<Equipo> equipos) {
		this.equipos = equipos;
	}

}
