package edu.server.repositorio;
// Generated 16-oct-2012 11:52:04 by Hibernate Tools 3.4.0.CR1

/**
 * SubclaseEquipoId generated by hbm2java
 */
public class SubclaseEquipoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7947731057934054344L;
	private int idSubclaseEquipo;
	private int idClaseEquipo;

	public SubclaseEquipoId() {
	}

	public SubclaseEquipoId(int idSubclaseEquipo, int idClaseEquipo) {
		this.idSubclaseEquipo = idSubclaseEquipo;
		this.idClaseEquipo = idClaseEquipo;
	}

	public int getIdSubclaseEquipo() {
		return this.idSubclaseEquipo;
	}

	public void setIdSubclaseEquipo(int idSubclaseEquipo) {
		this.idSubclaseEquipo = idSubclaseEquipo;
	}

	public int getIdClaseEquipo() {
		return this.idClaseEquipo;
	}

	public void setIdClaseEquipo(int idClaseEquipo) {
		this.idClaseEquipo = idClaseEquipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubclaseEquipoId))
			return false;
		SubclaseEquipoId castOther = (SubclaseEquipoId) other;

		return (this.getIdSubclaseEquipo() == castOther.getIdSubclaseEquipo())
				&& (this.getIdClaseEquipo() == castOther.getIdClaseEquipo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSubclaseEquipo();
		result = 37 * result + this.getIdClaseEquipo();
		return result;
	}

}
